In [1]:
pip install pandas geopy tqdm

Requirement already satisfied: pandas in c:\users\proje pc 13900k\anaconda3\lib\site-packages (2.2.3)
Collecting geopy
  Downloading geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: tqdm in c:\users\proje pc 13900k\anaconda3\lib\site-packages (4.67.1)
Requirement already satisfied: numpy>=1.23.2 in c:\users\proje pc 13900k\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\proje pc 13900k\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\proje pc 13900k\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\proje pc 13900k\anaconda3\lib\site-packages (from pandas) (2025.2)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: colorama in c:\users\proje pc 13900k\anaconda3\lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\users\proje pc 13900k\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading geopy-2.4.1-py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/125.4 kB ? eta -:--:--
   --- ------------------------------------ 10.2/125.4 kB ? eta -:--:--
   --------- ----------------------------- 30.7/125.4 kB 435.7 kB/s eta 0:00:01
   ------------ -------------------------- 41.0/125.4 kB 330.3 kB/s eta 0:00:01
   ---------------------------- ---------- 92.2/125.4 kB 525.1 kB/s eta 0:00:01
   ---------------------------- ---------- 92.2/125.4 kB 525.1 kB/s eta 0:00:01
   -------------------------------------- 125.4/125.4 kB 492.3 kB/s eta 0:00:00
Downloading geographiclib-2.1-py3-none-any.whl (40 kB)
   ---------------------------------------- 0.0/40.7 kB ? eta -:--:--
   ---------------------------------------- 40.7/40.7 kB 1.9 MB/s eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.1 geopy-2.4.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
# osm_match_schools_batch_fixed.py

import os
import re
import time
import pandas as pd
import requests
from difflib import SequenceMatcher
from tqdm import tqdm

# ===================== НАСТРОЙКИ =====================
IN_CSV  = "kindergartens_almaty_private.csv"
OUT_CSV = "kindergartens_almaty_private_osm_matched.csv"
OSM_DUMP_CSV = "almaty_osm_schools_dump.csv"
NOT_FOUND_CSV = "kindergartens_almaty_private_osm_not_found.csv"

# bbox Алматы
BBOX = (43.10, 76.70, 43.45, 77.15)

OVERPASS_URLS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.openstreetmap.ru/api/interpreter",
]

HEADERS = {"User-Agent": "almaty-osm-school-matcher/2.0"}

ALMATY_LAT = 43.2389
ALMATY_LON = 76.8897

# ===================== OSM =====================
def download_osm_schools(bbox):
    south, west, north, east = bbox

    q = f"""
    [out:json][timeout:180];
    (
        node["amenity"="kindergarten"]({south},{west},{north},{east});
        way["amenity"="kindergarten"]({south},{west},{north},{east});
        relation["amenity"="kindergarten"]({south},{west},{north},{east});

        // иногда размечены как building
        node["building"="kindergarten"]({south},{west},{north},{east});
        way["building"="kindergarten"]({south},{west},{north},{east});
        relation["building"="kindergarten"]({south},{west},{north},{east});
    );
    out center tags;
    """

    for base in OVERPASS_URLS:
        for attempt in range(5):
            try:
                r = requests.post(base, data=q.encode("utf-8"), headers=HEADERS, timeout=240)
                if r.status_code in (429, 502, 503, 504):
                    time.sleep(2 * (attempt + 1))
                    continue

                r.raise_for_status()
                js = r.json()

                rows = []
                for e in js.get("elements", []):
                    tags = e.get("tags", {}) or {}

                    if e["type"] == "node":
                        lat, lon = e.get("lat"), e.get("lon")
                    else:
                        c = e.get("center") or {}
                        lat, lon = c.get("lat"), c.get("lon")

                    if lat is None or lon is None:
                        continue

                    rows.append({
                        "osm_type": e["type"],
                        "osm_id": e["id"],
                        "name": tags.get("name"),
                        "name_ru": tags.get("name:ru"),
                        "lat": lat,
                        "lon": lon,
                    })

                return pd.DataFrame(rows)

            except Exception:
                time.sleep(2)

    raise RuntimeError("Overpass failed")

# ===================== MATCHING =====================
def norm(s):
    if s is None:
        return ""
    s = str(s).lower()
    s = s.replace("ё", "е").replace("№", " no ")
    s = re.sub(r"[^0-9a-zа-я\s]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def extract_number(s):
    s = norm(s)
    m = re.search(r"\bno\s*(\d+)", s)
    if m:
        return m.group(1)
    m = re.search(r"школ[а-я]*\s*(\d+)", s)
    if m:
        return m.group(1)
    return None

def similarity(a, b):
    return SequenceMatcher(None, a, b).ratio()

def best_match(name, osm):
    target = norm(name)
    num = extract_number(name)

    cand = osm
    if num:
        tmp = osm[osm["name_norm"].str.contains(num, na=False)]
        if len(tmp) > 0:
            cand = tmp

    exact = cand[cand["name_norm"] == target]
    if len(exact) > 0:
        r = exact.iloc[0]
        return r, "exact", 1.0

    best = None
    best_score = 0

    for _, r in cand.iterrows():
        sc = similarity(target, r["name_norm"])
        if sc > best_score:
            best_score = sc
            best = r

    if best_score < (0.62 if num else 0.72):
        return None, None, None

    return best, "fuzzy", best_score

# ===================== GEOCODERS =====================
def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15

photon_cache = {}
def photon_geocode(q):
    if q in photon_cache:
        return photon_cache[q]

    url = "https://photon.komoot.io/api"
    try:
        r = requests.get(url, params={"q": q, "limit": 1}, timeout=10)
        js = r.json()
        feats = js.get("features", [])
        if feats:
            lon, lat = feats[0]["geometry"]["coordinates"]
            if in_bbox(lat, lon):
                photon_cache[q] = (lat, lon)
                return lat, lon
    except:
        pass

    photon_cache[q] = (None, None)
    return None, None

# ===================== MAIN =====================
def main():
    df = pd.read_csv(IN_CSV)

    # OSM
    if os.path.exists(OSM_DUMP_CSV):
        osm = pd.read_csv(OSM_DUMP_CSV)
    else:
        osm = download_osm_schools(BBOX)
        osm.to_csv(OSM_DUMP_CSV, index=False)

    osm["name_best"] = osm["name_ru"].fillna(osm["name"]).fillna("")
    osm["name_norm"] = osm["name_best"].apply(norm)

    # OUTPUT
    out = df.copy()
    out["lat"] = None
    out["lon"] = None
    out["method"] = None
    out["score"] = None

    # 1. OSM matching
    for i, row in tqdm(out.iterrows(), total=len(out)):
        res, method, score = best_match(row["name"], osm)
        if res is not None:
            out.at[i, "lat"] = res["lat"]
            out.at[i, "lon"] = res["lon"]
            out.at[i, "method"] = method
            out.at[i, "score"] = score

    # 2. Photon fallback
    for i in tqdm(out[out["lat"].isna()].index):
        addr = str(out.at[i, "address"])
        lat, lon = photon_geocode(addr + ", Алматы")

        if lat:
            out.at[i, "lat"] = lat
            out.at[i, "lon"] = lon
            out.at[i, "method"] = "photon"

        time.sleep(0.2)

    # 3. Nominatim fallback
    from geopy.geocoders import Nominatim
    from geopy.extra.rate_limiter import RateLimiter

    geo = Nominatim(user_agent="almaty-final")
    geocode = RateLimiter(geo.geocode, min_delay_seconds=1)

    for i in tqdm(out[out["lat"].isna()].index):
        addr = str(out.at[i, "address"])
        try:
            loc = geocode(addr + ", Алматы, Казахстан")
            if loc and in_bbox(loc.latitude, loc.longitude):
                out.at[i, "lat"] = loc.latitude
                out.at[i, "lon"] = loc.longitude
                out.at[i, "method"] = "nominatim"
        except:
            pass

    # confidence
    def conf(row):
        if row["method"] == "exact":
            return "high"
        if row["method"] == "fuzzy" and row["score"] > 0.8:
            return "high"
        if row["method"] in ["photon", "nominatim"]:
            return "medium"
        return "low"

    out["confidence"] = out.apply(conf, axis=1)

    out.to_csv(OUT_CSV, index=False)
    out[out["lat"].isna()].to_csv(NOT_FOUND_CSV, index=False)

    print("DONE")
    print("Found:", out["lat"].notna().sum())
    print("Not found:", out["lat"].isna().sum())

if __name__ == "__main__":
    main()

100%|██████████| 730/730 [00:09<00:00, 73.26it/s]
100%|██████████| 462/462 [05:57<00:00,  1.29it/s]
100%|██████████| 462/462 [07:49<00:00,  1.02s/it]

DONE
Found: 575
Not found: 155

In [3]:
import pandas as pd
import re
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from tqdm import tqdm

df = pd.read_csv("kindergartens_almaty_private_osm_matched.csv")

# viewbox Алматы
ALMATY_VIEWBOX = [(43.10, 76.70), (43.45, 77.15)]

geolocator = Nominatim(user_agent="almaty-clean-pass", timeout=20)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)


def clean_address(addr):
    if pd.isna(addr):
        return ""

    s = str(addr)
    s = s.replace("мкр.", "микрорайон")
    s = s.replace("ул.", "улица")
    s = s.replace("пр.", "проспект")
    s = re.sub(r"\s+", " ", s).strip(" ,")
    return s


def address_variants(addr):
    a = clean_address(addr)
    variants = [a]

    # без микрорайона
    v2 = re.sub(r"микрорайон[^,]+,\s*", "", a, flags=re.IGNORECASE)
    variants.append(v2)

    # только улица + дом
    m = re.search(r"(улица[^,]+,\s*\d+\w?)", a, flags=re.IGNORECASE)
    if m:
        variants.append(m.group(1))

    # убрать слова
    v4 = re.sub(r"(микрорайон|улица|проспект)", "", a, flags=re.IGNORECASE)
    variants.append(v4)

    # удалить пустые
    return list(dict.fromkeys([v.strip(" ,") for v in variants if v.strip()]))


def geo(q):
    try:
        loc = geocode(q, viewbox=ALMATY_VIEWBOX, bounded=True, country_codes="kz")
        if loc:
            return loc.latitude, loc.longitude
    except:
        pass
    return None, None


mask = df["lat"].isna()

for i in tqdm(df[mask].index):
    addr = df.loc[i, "address"]

    for v in address_variants(addr):
        lat, lon = geo(v + ", Алматы, Казахстан")
        if lat is not None:
            df.loc[i, "lat"] = lat
            df.loc[i, "lon"] = lon
            df.loc[i, "match_method"] = "clean_retry"
            break

df.to_csv("kindergartens_almaty_private_osm_matched_final.csv", index=False)

print("Найдено:", df["lat"].notna().sum())
print("Не найдено:", df["lat"].isna().sum())

100%|██████████| 155/155 [03:58<00:00,  1.54s/it]

Найдено: 676
Не найдено: 54

In [12]:
df['money']='yes'

In [2]:
import pandas as pd
df = pd.read_csv("kindergartens_almaty_private_osm_matched_final.csv")

In [25]:
df.to_csv("kindergartens_almaty_private_osm_matched_final.csv", index=False)

In [24]:
not_found = df[df["lat"].isna()].copy()
not_found

Empty DataFrame
Columns: [name, address, phone, type, email, lat, lon, method, score, confidence, match_method, money]
Index: []

In [23]:
df.loc[df['name']=='Мини-центр "Медина-А"', 'lat'] = 43.174623
df.loc[df['name']=='Мини-центр "Медина-А"', 'lon'] = 76.795665

df.loc[df['name']=='Мини-центр "Медина-лидер"', 'lat'] = 43.20419
df.loc[df['name']=='Мини-центр "Медина-лидер"', 'lon'] = 76.802443

df.loc[df['name']=='Детский сад "Малика-2023"', 'lat'] = 43.22174
df.loc[df['name']=='Детский сад "Малика-2023"', 'lon'] = 76.791499

df.loc[df['name']=='Детский центр "Kinder land"', 'lat'] = 43.191871
df.loc[df['name']=='Детский центр "Kinder land"', 'lon'] = 76.815331

df.loc[df['name']=='Детский сад "Дарын2024"', 'lat'] = 43.191871
df.loc[df['name']=='Детский сад "Дарын2024"', 'lon'] = 76.815331

df.loc[df['name']=='Детский сад "Care Kids"', 'lat'] = 43.325604
df.loc[df['name']=='Детский сад "Care Kids"', 'lon'] = 76.981351
df.loc[df['name']=='Детский сад "Care Kids"', 'address'] = 'мкрн Жас Канат 550'

In [20]:
df[df['name']=='Детский сад "I-NAZ KIDS"']

,name,address,phone,type,email,lat,lon,method,score,confidence,match_method,money
224,"Детский сад ""I-NAZ KIDS""","ул.Шакшак Жанибека, 45/2","87018448740, 87273992587",детский сад,nurbekova_gaziza@mail.ru,43.273387,76.974304,NaN,NaN,low,NaN,yes

In [30]:
df[df.duplicated(subset=['lat', 'lon'])==True]

,name,address,phone,type,email,lat,lon,method,score,confidence,match_method,money
10,"Детский сад ""Аиша""","ул. Саялы, 14","87473002512, 87272514252",детский сад,akhat54@mail.ru,43.250226,76.899419,fuzzy,0.875000,high,NaN,yes
11,"Детский сад ""Мимишка""","ул. Димитрова, 10","87757526846, 87272570137",детский сад,mimishka_18@mail.ru,43.250226,76.899419,fuzzy,0.742857,low,NaN,yes
21,Детский сад «Гусельки»,"ул. Степана Разина, 94","87079614471, 87273854286",детский сад,guselki09@mail.ru,43.250226,76.899419,fuzzy,0.777778,low,NaN,yes
24,"Детский сад ""КҮН ШУАҚ""","ул. Дунентаева, 6/4","87016017606, 87016017606",детский сад,kun-shuak@mail.ru,43.250226,76.899419,fuzzy,0.742857,low,NaN,yes
30,"Детский сад ""АЗИМКА""","ул. Дегдара, 36/1","87071288851, 87071288851",детский сад,indigo2101@mail.ru,43.250226,76.899419,fuzzy,0.823529,high,NaN,yes
...,...,...,...,...,...,...,...,...,...,...,...,...
686,"ТОО ""АҚСАУЛЕ 2023""","мкр. Туркестан, 77","87074485570, 87074485570",детский сад,inkar_12@mail.ru,43.271812,76.852261,NaN,NaN,low,clean_retry,yes
693,"ТОО детский сад ""BB DAmir""","ул. Асанова, 7","87479582092, 87479582092",детский сад,damir.bb@bk.ru,43.337561,77.068094,NaN,NaN,low,clean_retry,yes
699,"ТОО ""Детский сад ""Мың бала Алматы""","ул. Казтуган Жырау, 29/1","87076602011, 87079335616",детский сад,mynbala2023@gmail.com,43.247665,76.813290,nominatim,NaN,medium,NaN,yes
705,"ТОО ""Детский сад Хан""","ул. Розыбакиева, 9","87075533537, 87478844851",детский сад,ail_220222@mail.ru,43.250226,76.899419,fuzzy,0.742857,low,NaN,yes
711,"АО детский сад ""Бахус""","ул. Карасай Батыра, 175","87017121405, 87273755453",детский сад,nurcolosok@mail.ru,43.250226,76.899419,fuzzy,0.722222,low,NaN,yes

In [34]:
dups = df[df.duplicated(subset=['lat', 'lon'], keep=False)].sort_values(['lat', 'lon'])
print(dups[['name', 'address', 'lat', 'lon', 'method', 'score']].to_string())

                                                                  name                      address        lat        lon           method     score
403                                                 Детский сад "Нэмо"          мкр. Атамекен, 163А  43.207334  76.849053  nominatim_dedup  0.814815
405                               Детский сад "Білім балалар орталығы"          мкр. Атамекен, 163А  43.207334  76.849053              NaN       NaN
425                                   Детский-ясли сад "Береке - 2020"          мкр. Атамекен, 33/1  43.207593  76.844508  nominatim_dedup  0.723404
476                                        Детский сад "Тимас компани"          мкр. Атамекен, 33/1  43.207593  76.844508              NaN       NaN
387                                       Детский сад "Altyn Gasyr_KZ"             мкр. Мамыр-7, 21  43.212152  76.840487              NaN       NaN
440                                      Детский сад "Antaress kids-2"              мкр. Алмас, 106  43.212152  76.840487  nominatim_dedup       NaN
451                                               Детский сад "Айсана"              мкр. Алмас, 134  43.212152  76.840487  nominatim_dedup  0.823529
473                                             Детский сад "Ару kids"              мкр. Алмас, 201  43.212152  76.840487  nominatim_dedup  0.722222
493                                            Детский сад "Садок ltd"              мкр. Алмас, 172  43.212152  76.840487  nominatim_dedup  0.756757
431                                                Мини-центр "i.Bala"             мкр. Мамыр 4, 18  43.214040  76.854358              NaN       NaN
467                                             Детский сад "i.Bala 2"             мкр. Мамыр 4, 18  43.214040  76.854358  nominatim_dedup  0.756757
337                                          Детский сад "ERKE A kids"          ул. Тажибаевой, 180  43.214124  76.891300        nominatim       NaN
384                                    Детский сад "Joy Art Education"          ул. Тажибаевой, 180  43.214124  76.891300        nominatim       NaN
404                                           Детский сад "Таргап А&K"            мкр. Мамыр 4, 128  43.214311  76.844594              NaN       NaN
486                                               Детский сад "ШамШер"            мкр. Мамыр 4, 128  43.214311  76.844594  nominatim_dedup  0.764706
394                                          Детский сад "Lion Garden"              мкр. Алмас, 57а  43.214799  76.869270              NaN       NaN
443                                                 Детский сад "УМКА"            мкр. Мамыр-4, 57А  43.214799  76.869270  nominatim_dedup  0.814815
397                                             Детский сад "Умка Сад"            мкр. Мамыр-4, 166  43.215713  76.852208  nominatim_dedup  0.777778
435                                               Детский сад "Эврика"             мкр. Мамыр 4, 4Б  43.215713  76.852208  nominatim_dedup  0.810811
461                                                Детский сад "Білім"             мкр. Мамыр 4, 4б  43.215713  76.852208  nominatim_dedup  0.787879
416                                       Мини-центр "Новое поколение"            мкр. Мамыр 7, 8/1  43.215754  76.837410              NaN       NaN
420                                     Мини-центр "ДиДи2016" (филиал)            мкр. Мамыр-7, 8/1  43.215754  76.837410  nominatim_dedup       NaN
412                                        Детский сад "Antaress Kids"            мкр. Мамыр-4, 156  43.216051  76.849806              NaN       NaN
494                                               Мини-центр "АйДиНур"            мкр. Мамыр 4, 156  43.216051  76.849806  nominatim_dedup       NaN
100                                           Детский сад "CӘТ-БЕРЕКЕ"         ул. Жунисова, 134/80  43.218856  76.790825  nominatim_dedup  0.829268
106                                          Детский сад "Aizere 2020"           ул. Жунисова, 2/87  43.218856  76.790825        nominatim       NaN
127                                            Мини-центр "Чудо-детки"              ул. Таргап, 111  43.219009  76.795306        nominatim       NaN
162                                       Детский сад "Smart Children"              ул. Таргап, 111  43.219009  76.795306        nominatim       NaN
78   Детский сад "Алматинская математико-лингвистическая школа "Самай"       ул. Аширбек Сыгай, 124  43.220923  76.792445        nominatim       NaN
82                                        Детский сад "Munarat Almaty"        ул. Аширбек Сыгай, 96  43.220923  76.792445  nominatim_dedup       NaN
227                                        Детский сад "Villa Bambini"            ул. Таттимбета, 3  43.223372  76.967799        nominatim       NaN
248                                      Детский сад "Чудесная страна"            ул. Таттимбета, 3  43.223372  76.967799        nominatim       NaN
134                                           Детский сад "Бала-Дария"          ул. Айбергенова, 92  43.223932  76.796668  nominatim_dedup  0.736842
137                                               Детский сад "Сұңқар"          ул. Айбергенова, 92  43.223932  76.796668  nominatim_dedup  0.875000
468                                               Детский Центр "Умка"            мкр. Аксай 3а, 85  43.235693  76.826545  nominatim_dedup       NaN
481                                   Детский сад "СӘТТІЛІК & БОЛАШАҚ"             мкр. Мамыр 3, 3А  43.235693  76.826545              NaN       NaN
278                                            Детский сад "Parasat-S"       мкр. Айнабулак-3, 172Е  43.236392  76.945728              NaN       NaN
474                                                Детский сад "Зере "           мкр. Атамекен, 70Б  43.236392  76.945728  nominatim_dedup  0.857143
550                                                Детский сад "Арман"        мкр. Мадениет, 288/30  43.236392  76.945728  nominatim_dedup  0.787879
456                                    Образовательный центр "Арайлым"             мкр. Баянаул, 40  43.239704  76.819395  nominatim_dedup  0.758621
497                                        Детский сад "Мир детства 1"             мкр. Баянаул, 40  43.239704  76.819395              NaN       NaN
580                                         Детский сад "Болашақ и Со"       ул. Казтуган Жырау, 21  43.247665  76.813290        nominatim       NaN
699                                 ТОО "Детский сад "Мың бала Алматы"     ул. Казтуган Жырау, 29/1  43.247665  76.813290  nominatim_dedup       NaN
567                                          Мини-центр "ЕЛАМАН-КЫЗЫР"             ул. Чуланова, 83  43.253778  76.828289        nominatim       NaN
652                                        ТОО детский сад "БАЛ САПАР"             ул. Чуланова, 83  43.253778  76.828289        nominatim       NaN
522                                 Детский сад "Алди-Ерке-1" (филиал)           мкр. Туркестан, 77  43.271812  76.852261              NaN       NaN
686                                                 ТОО "АҚСАУЛЕ 2023"           мкр. Туркестан, 77  43.271812  76.852261              NaN       NaN
556                                           Детский сад "Кун Шуак-М"           ул. Туймебаева, 68  43.275548  76.834737        nominatim       NaN
624                                       ТОО "BAL-bala 1 балабақшасы"           ул. Туймебаева, 39  43.275548  76.834737  nominatim_dedup       NaN
528                                        Детский сад "Мерей компани"                ул. Текес, 67  43.284888  76.836085  nominatim_dedup  0.772727
592                                      ТОО детский сад "Төре - Зере"                ул. Текес, 79  43.284888  76.836085        nominatim       NaN
39                                          Мини-центр "ЕРКЕМ-АЙ ГОЛД"             ул. Ижевская, 33  43.294301  76.962759        nominatim       NaN
49                                             Детский сад "Балдаурен"             ул. Ижевская, 33  43.294301  76.962759  nominatim_dedup  0.750000
3                                       Мини-центр "Немере и компания"       ул. Каракалпакская, 12  43.296459  76.963379        nominatim       NaN
46                                            Детский сад "Bakutalemi"       ул. Каракалпакская, 12  43.296459  76.963379        nominatim       NaN
553                                              Детский сад "Зерде-2"             ул. Тайконыр, 41  43.300208  76.890733  nominatim_dedup  0.789474
581                                                Детский сад "Зерде"             ул. Тайконыр, 41  43.300208  76.890733  nominatim_dedup  0.833333
651                                          ТОО Ясли сад «Happy kids»     ул. Кожаберген Жырау, 19  43.327219  76.897735        nominatim       NaN
667                                       ТОО детский сад "Бақыт нұры"     ул. Кожаберген Жырау, 19  43.327219  76.897735        nominatim       NaN
626                                           ТОО "Балабакша "Болашақ"              ул. Асанова, 77  43.337561  77.068094              NaN       NaN
693                                         ТОО детский сад "BB DAmir"               ул. Асанова, 7  43.337561  77.068094  nominatim_dedup       NaN
36                                            Детский сад "Жансая-Сәт"              ул. Зимняя, 18Б  43.352260  76.986999  nominatim_dedup  0.736842
44                                              Детский сад "Биржан К"                ул. Зимняя, 2  43.352260  76.986999  nominatim_dedup  0.777778
24                                              Детский сад "КҮН ШУАҚ"          ул. Дунентаева, 6/4  43.357280  76.995136  nominatim_dedup  0.742857
47                                               Детский сад "Кокетай"          ул. Дунентаева, 8/1  43.357280  76.995136  nominatim_dedup  0.742857
30                                                Детский сад "АЗИМКА"            ул. Дегдара, 36/1        NaN        NaN              NaN  0.823529
85                                         Детский центр "Kinder land"         ул. Ш. Айтматова, 71        NaN        NaN              NaN       NaN
92                                            Детский сад "Top Kids 2"           ул. Кенжетаев, 119        NaN        NaN              NaN  0.769231
101                                             Детский сад "Top Kids"           ул. Кенжетаев, 121        NaN        NaN              NaN  0.756757
142                                              Детский сад "Тамирис"        ул. Кенесары-Хан, 116        NaN        NaN              NaN  0.800000
143                                               Детский сад "Талшын"          ул. Сейитбекова, 43        NaN        NaN              NaN  0.764706
144                                   Детский сад «Бала- Дария» филиал        ул. Аширбек Сыгай, 55        NaN        NaN              NaN       NaN
145                                               Детский сад "Асылым"             ул. Ашимова, 259        NaN        NaN              NaN  0.764706
147                                                Детский сад "АЯНАТ"             ул. Аскарова, 28        NaN        NaN              NaN  0.787879
148                                           Детский сад "Дария Айша"         ул. Қыдырбеков, 60/1        NaN        NaN              NaN  0.736842
152                                               Детский сад "ALATAU"              ул. Афцинао, 11        NaN        NaN              NaN  0.758621
157                                         Детский сад "MARY POPPINS"      ул. Кали-Надырова, 98/1        NaN        NaN              NaN       NaN
158                                              Детский сад "ЛИМПОПО"        ул. Аширбек Сыгай, 71        NaN        NaN              NaN  0.742857
160                                           Детский сад "БАТЫР-ШИФА"         ул. Кали Надырова, 4        NaN        NaN              NaN  0.736842
165                                              Детский сад "Балапан"              ул. Жалкамыс, 1        NaN        NaN              NaN  0.742857
166                                              Детский сад "Нұрбөпе"  ул. Герольда Бельгера, 57/1        NaN        NaN              NaN  0.742857
167                                             Детский сад "Ерсинтай"         ул. Аспандиярова, 83        NaN        NaN              NaN  0.777778
168                                            Детский сад "ЖАСДИМЕЙР"             ул. Кыдырова, 13        NaN        NaN              NaN  0.756757
169                                         Детский сад "Кенгуренок-А"           ул. Сейтметова, 87        NaN        NaN              NaN  0.790698
179                                             Детский сад "Бала шак"               ул. Акбата, 68        NaN        NaN              NaN  0.722222
182                                             Детский сад "Сарқыт-А"      ул. Болатхан Тайжан, 29        NaN        NaN              NaN  0.777778
183                                             Детский сад "Ақ-Аянұр"        ул. Ибрая Жакаева, 85        NaN        NaN              NaN  0.742857
184                                               Детский сад "Баттыл"              ул. Қарлығаш, 7        NaN        NaN              NaN  0.764706
185                                            Детский сад «АЙГОЛЕК-1»           ул. Сейтметов, 102        NaN        NaN              NaN  0.736842
186                                                  Детский сад "Ади"          ул. Даулеткерей, 25        NaN        NaN              NaN  0.903226
188                                              Детский сад "Bаmbino"        ул. Кыдырбекова, 60/1        NaN        NaN              NaN  0.777778
189                                              Детский сад " Радуга"               ул. Таргап, 11        NaN        NaN              NaN  0.764706
190                                                Детский сад "Жануя"              ул. Бекешева, 4        NaN        NaN              NaN  0.787879
198                                                Детский сад "Адеми"          ул. Луганского, 151        NaN        NaN              NaN  0.848485
203                                              Детский сад "SymLynn"            ул. Затаевича, 77        NaN        NaN              NaN  0.733333
204                                              Детский сад "Koktobe"          ул. Найманбаева, 95        NaN        NaN              NaN  0.733333
205                                             Детский сад "Балбөбек"     Территория СТ Жетысу, 39        NaN        NaN              NaN  0.722222
207                                             Детский сад "Батыр Ел"           ул. Верненская, 73        NaN        NaN              NaN  0.722222
208                                              Детский сад "Ботақан"         ул. Есенберлина, 155        NaN        NaN              NaN  0.742857
211                                               Детский сад "My kid"             ул. Аманжола, 54        NaN        NaN              NaN  0.758621
214                                              Детский сад "Alishka"           ул. Янушкевича, 49        NaN        NaN              NaN  0.733333
217                                                Детский сад "Панда"           ул. Орманова, 32 А        NaN        NaN              NaN  0.787879
219                                                 Детский сад "Rani"             ул. Жиренше, 75а        NaN        NaN              NaN  0.814815
220                                             Детский сад "ErnarRai"    ул. Шакшак Жанибека, 45/1        NaN        NaN              NaN       NaN
221                                            Детский сад "Нұр-Айбек"         Улица Каркаралы, 27а        NaN        NaN              NaN  0.756757
226                                               Детский сад "Талант"              ул. Митина, 23А        NaN        NaN              NaN  0.764706
228                                                Ясли-сад "Еркем-Ай"            ул. Жамакаева, 93        NaN        NaN              NaN  0.838710
231                                              Детский сад "Еркетай"           ул. Каркаралы, 23а        NaN        NaN              NaN  0.842105
234                                              Детский сад «Эльсана»              ул. Зверева, 28        NaN        NaN              NaN  0.800000
235                                                Детский сад "StArt"            ул. Кармысова, 90        NaN        NaN              NaN  0.785714
239                                              Детский сад "KULPASH"            ул. Жуковского, 7        NaN        NaN              NaN  0.733333
240                                              Детский сад "АлдиАмир              ул. Сырмак, 44А        NaN        NaN              NaN  0.777778
241                                               Детский сад "Аликош"              ул. Домбыра, 28        NaN        NaN              NaN  0.823529
246                                             Детский сад «Aqbesik»"              ул. Клубная, 24        NaN        NaN              NaN  0.733333
249                                             Детский сад "Бэби Сад"           ул. Каирбекова, 37        NaN        NaN              NaN  0.777778
250                                              Детский сад "Березка"          ул. Рубинштейна, 3а        NaN        NaN              NaN  1.000000
253                                                Детский сад "Alina"           ул. Каирбекова, 68        NaN        NaN              NaN  0.785714
254                                              Детский сад "Умняшка"          ул. Ибрагимова, 105        NaN        NaN              NaN  0.742857
259                                                Детский сад "Алина"            ул. Сахариева, 11        NaN        NaN              NaN  0.848485
260                                            Детский сад "Дана Бала"             ул. Текемет, 40а        NaN        NaN              NaN  0.756757
261                                           Детский сад "BabyBoom 3"             ул. Поповича, 45        NaN        NaN              NaN  0.750000
263                                               Детский сад "GRAMMY"            ул. Жамакаева, 46        NaN        NaN              NaN  0.758621
265                                             Детский сад "TILVALDY"      ул. Нурмагамбетова, 202        NaN        NaN              NaN       NaN
271                                              Детский сад "Ai-bota"              ул. Аныракай, 6        NaN        NaN              NaN  0.733333
274                                                Детский сад «Bambi»       мкр. Айнабулак-4, 167а        NaN        NaN              NaN  0.785714
275                                              Детский сад "Львёнок"          ул. Жансугуров, 250        NaN        NaN              NaN  0.736842
284                                              Детский сад "АДИНА-Д"               ул. Табигат, 1        NaN        NaN              NaN  0.800000
288                                           Детский сад "Мадина -27"          ул. Молодежная, 69А        NaN        NaN              NaN  0.756757
289                                             Детский сад "Дария 23"         ул. Пестковского, 54        NaN        NaN              NaN  0.777778
294                                                Детский сад "Тедди"         ул. Венецианова, 21А        NaN        NaN              NaN  0.787879
295                                              Детский сад "Умит Ай"             мкр. Кокжиек, 7а        NaN        NaN              NaN  0.742857
297                                                 Детский сад "Аиша"                ул. Саялы, 14        NaN        NaN              NaN  0.875000
298                                               Детский сад "Ай-Лау"           ул. Фаворского, 12        NaN        NaN              NaN  0.764706

In [32]:
import pandas as pd
import requests
import time

df = pd.read_csv("kindergartens_almaty_private_osm_matched_final.csv")

def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15

def photon_geocode(q):
    try:
        r = requests.get("https://photon.komoot.io/api", 
                         params={"q": q, "limit": 3}, timeout=10)
        for feat in r.json().get("features", []):
            lon, lat = feat["geometry"]["coordinates"]
            if in_bbox(lat, lon):
                return lat, lon
    except:
        pass
    return None, None

# Найти дупликаты с разными адресами
dup_mask = df.duplicated(subset=['lat', 'lon'], keep=False)
dups = df[dup_mask].copy()

# Для каждой группы дупликатов — оставить первую запись, остальным сбросить координаты
rows_to_fix = []
for (lat, lon), group in dups.groupby(['lat', 'lon']):
    # Если адреса разные — все кроме первой нужно перегеокодировать
    unique_addresses = group['address'].nunique()
    if unique_addresses > 1:
        rows_to_fix.extend(group.index[1:].tolist())  # все кроме первой

print(f"Строк для перегеокодирования: {len(rows_to_fix)}")

# Перегеокодировать через Photon
for i in rows_to_fix:
    addr = df.loc[i, 'address']
    lat, lon = photon_geocode(f"{addr}, Алматы, Казахстан")
    if lat:
        df.loc[i, 'lat'] = lat
        df.loc[i, 'lon'] = lon
        df.loc[i, 'method'] = 'photon_dedup'
        print(f"✓ {df.loc[i, 'name']} → {lat:.5f}, {lon:.5f}")
    else:
        # Сбросить — лучше NaN чем неверные координаты
        df.loc[i, 'lat'] = None
        df.loc[i, 'lon'] = None
        df.loc[i, 'method'] = None
        print(f"✗ Не найдено: {df.loc[i, 'name']} | {addr}")
    time.sleep(0.3)

# Проверка результата
print(f"\nОсталось дупликатов: {df.duplicated(subset=['lat','lon']).sum()}")
print(f"Не найдено координат: {df['lat'].isna().sum()}")

df.to_csv("kindergartens_almaty_private_osm_matched_final.csv", index=False)

Строк для перегеокодирования: 273
✗ Не найдено: Детский сад "Tarlan kids" | ул. Кенесары хан, 67
✗ Не найдено: Детский сад "MARY POPPINS" | ул. Кали-Надырова, 98/1
✗ Не найдено: Филиал "Образовательного комплекса школы "First" | мкр. Мирас, 59
✗ Не найдено: Детский сад «Sparks Preschool» | мкр. Мирас, 160
✗ Не найдено: Детский центр "Kinder land" | ул. Ш. Айтматова, 71
✗ Не найдено: Детский сад "Р-Мурагер 2" | ул. Санаторная, 12
✗ Не найдено: Детский сад "Antaress kids-2" | мкр. Алмас, 106
✗ Не найдено: Мини-центр "ДиДи2016" (филиал) | мкр. Мамыр-7, 8/1
✗ Не найдено: Мини-центр "АйДиНур" | мкр. Мамыр 4, 156
✗ Не найдено: Образовательный центр "Арайлым" | мкр. Баянаул, 40
✗ Не найдено: Ақниет Образовательный Центр | мкр. Мамыр 4, 58
✗ Не найдено: Образовательный центр "Алладин" | ул. Кокшокы, 6а
✗ Не найдено: Детский сад "Munarat Almaty" | ул. Аширбек Сыгай, 96
✗ Не найдено: Детский сад «Бала- Дария» филиал | ул. Аширбек Сыгай, 55
✗ Не найдено: Детский сад «АкЕрке" | ул. Белбулак, 20
✗ Не найдено: Детский сад "Балдаурен" | ул. Ижевская, 33
✗ Не найдено: Детский ясли-сад "Еркетай" | ул. Соболева, 164
✗ Не найдено: Детский сад "АЙЗЕРЕ и К" | ул. Казангап, 21
✗ Не найдено: Детский сад "Береке - Мармар" | ул. Береке, 40
✗ Не найдено: Детский сад "CӘТ-БЕРЕКЕ" | ул. Жунисова, 134/80
✗ Не найдено: Детский сад "Кенгуренок-А" | ул. Сейтметова, 87
✗ Не найдено: Детский сад "Еркетай" | ул. Каркаралы, 23а
✗ Не найдено: Детский сад "Березка" | ул. Рубинштейна, 3а
✗ Не найдено: Детский сад "Львёнок" | ул. Жансугуров, 250
✗ Не найдено: Детский сад "Зайка" | ул. Маркова, 9
✗ Не найдено: Детский садик "Чебурашка" | мкр. Алтын бесик, 177
✗ Не найдено: Детский-ясли сад "Береке - 2020" | мкр. Атамекен, 33/1
✗ Не найдено: Детский сад "Эврика" | мкр. Мамыр 4, 4Б
✗ Не найдено: Детский сад «Еркежан» | мкр. Алтын бесік, 223
✗ Не найдено: Детский сад "Зере " | мкр. Атамекен, 70Б
✗ Не найдено: Детский сад " ТОЦ Өнер " | ул. Мухамеджанова, 42
✗ Не найдено: Детский сад "Ертарғын" | ул. Арқалық, 19/6
✗ Не найдено: Детский сад "Бексұлтан 7" | ул. Кокжайлау, 7
✗ Не найдено: Детский сад "Роза" | ул. Аубакирова, 118
✗ Не найдено: Детский сад "Мерей компани" | ул. Текес, 67
✗ Не найдено: Детский сад "Ерке" | ул. Ахметова, 57
✗ Не найдено: Детский сад "Зерде-2" | ул. Тайконыр, 41
✗ Не найдено: Детский сад «Ертөстік» | ул. Доспановой, 26
✗ Не найдено: Детский сад "Венера" | ул. Сапиева, 6
✗ Не найдено: Детский сад "Еркемай" | ул. Доспанова, 22
✗ Не найдено: Детский сад "Зерде" | ул. Тайконыр, 41
✗ Не найдено: детский сад "Балдаурен" | ул. Айналмалы, 138
✗ Не найдено: ТОО "Детский сад Бекося" | ул. Курти, 18
✗ Не найдено: ТОО детский сад "Еркеназ 1" | ул. Туйемойнак, 47а
✗ Не найдено: Детский сад "МЕГА КИДС" (филиал) | 11-я улица, 8
✗ Не найдено: Детский сад "Нұр Болашақ" | ул. Онгарсыновой, 15
✗ Не найдено: Детский сад "Top Kids 2" | ул. Кенжетаев, 119
✗ Не найдено: Детский сад "SUNSHINE 2" | ул. Актамберды жырау, 3
✗ Не найдено: Детский сад "Радуга 2" | ул. Таргап, 109
✗ Не найдено: Детский сад "АҚӘЛЕМ 2" | ул. Пролетарская, 15
✗ Не найдено: Детский сад "i.Bala 2" | мкр. Мамыр 4, 18
✗ Не найдено: Детский сад "Молдир-2" | ул. Жанкожа батыр, 73
✗ Не найдено: Детский сад "ERKETAI-2" | ул. Талбесик, 32
✗ Не найдено: Детский сад "Top Kids" | ул. Кенжетаев, 121
✗ Не найдено: Детский сад "Bаmbino" | ул. Кыдырбекова, 60/1
✗ Не найдено: Детский сад "Kun ai" | ул. Шаймерденова, 27/33
✗ Не найдено: ТОО детский сад "Хан-9" | ул. Аркалык, 25/1
✗ Не найдено: Детский Центр "Умка" | мкр. Аксай 3а, 85
✗ Не найдено: Детский сад «АЙГОЛЕК-1» | ул. Сейтметов, 102
✗ Не найдено: Детский сад "Қарлығаш1" | ул. Грушовая, 12а
✗ Не найдено: Детский сад "Асемгул-1" | мкр. Алтын Бесик, 53
✗ Не найдено: Детский сад "Alina-kids-1" | мкр. Мамыр-4, 210
✗ Не найдено: Детский сад "Нұр-Сәт1" | ул. Абылай хан, 10
✗ Не найдено: ТОО "Детский сад "Мың бала Алматы" | ул. Казтуган Жырау, 29/1
✗ Не найдено: Детский сад "BabyBoom 3" | ул. Поповича, 45
✗ Не найдено: Детский сад "TILVALDY" | ул. Нурмагамбетова, 202
✗ Не найдено: Детский сад "Аиша" | ул. Саялы, 14
✗ Не найдено: Детский сад "Мимишка" | ул. Димитрова, 10
✗ Не найдено: Детский сад «Гусельки» | ул. Степана Разина, 94
✗ Не найдено: Детский сад "КҮН ШУАҚ" | ул. Дунентаева, 6/4
✗ Не найдено: Детский сад "АЗИМКА" | ул. Дегдара, 36/1
✗ Не найдено: Детский сад "Тимошка" | ул. Толегена Тажибаева, 26а
✗ Не найдено: Детский сад "Жансая-Сәт" | ул. Зимняя, 18Б
✗ Не найдено: Детский сад «Карусель» | ул. Стахановская, 19
✗ Не найдено: Детский сад "Куанар" | ул. Топчиева, 31В
✗ Не найдено: Детский сад "Биржан К" | ул. Зимняя, 2
✗ Не найдено: Детский сад "Адель&F" | пр. Суюнбая, 661
✗ Не найдено: Детский сад "Кокетай" | ул. Дунентаева, 8/1
✗ Не найдено: Детский сад "Кошахан" | 22-я улица, 46
✗ Не найдено: Детский сад "Бақ - Бала" | ул. Баймагамбетова, 82/4
✗ Не найдено: Детский сад "3 Кита" | ул. Щелково, 1
✗ Не найдено: Детский сад "Аврора" | ул. Глинки, 4
✗ Не найдено: Детский сад «Малышарики» | 4-я улица, 10
✗ Не найдено: Детский сад "Аяу-Нұр" | 15-я улица, 8
✗ Не найдено: Детский сад "Шапағат" | ул. Таргап, 117
✗ Не найдено: Детский сад "Нұрбала" | ул. Телжан Шонанулы, 78
✗ Не найдено: Детский сад «Алихан» | ул. Нурпеисова, 204
✗ Не найдено: Детский сад "Сары Балапан" | ул. Тажибаева, 46
✗ Не найдено: Детский сад "Аңсаған-К" | ул. Ашимова, 343/2
✗ Не найдено: Детский сад "Би- Тұмар" | ул. Камысдала, 27
✗ Не найдено: Детский сад "Муслимхан" | ул. Аширбек Сыгай, 47
✗ Не найдено: Детский сад "Айымсұлу" | ул. Сагдиева, 63
✗ Не найдено: Детский сад "Бала-Дария" | ул. Айбергенова, 92
✗ Не найдено: Детский сад "Актыным" | ул. Жунисова, 53
✗ Не найдено: Детский сад "Сұңқар" | ул. Айбергенова, 92
✗ Не найдено: Детский сад "Нұр Дария" | ул. Айбергенова, 45
✗ Не найдено: Детский сад "Айдария" | ул. Сагдиев, 59
✗ Не найдено: Детский сад "Тамирис" | ул. Кенесары-Хан, 116
✗ Не найдено: Детский сад "Талшын" | ул. Сейитбекова, 43
✗ Не найдено: Детский сад "Асылым" | ул. Ашимова, 259
✗ Не найдено: Детский сад "АЯНАТ" | ул. Аскарова, 28
✗ Не найдено: Детский сад "Дария Айша" | ул. Қыдырбеков, 60/1
✗ Не найдено: Детский сад "ЛИМПОПО" | ул. Аширбек Сыгай, 71
✗ Не найдено: Детский сад "БАТЫР-ШИФА" | ул. Кали Надырова, 4
✗ Не найдено: Детский сад "Балапан" | ул. Жалкамыс, 1
✗ Не найдено: Детский сад "Нұрбөпе" | ул. Герольда Бельгера, 57/1
✗ Не найдено: Детский сад "Ерсинтай" | ул. Аспандиярова, 83
✗ Не найдено: Детский сад "ЖАСДИМЕЙР" | ул. Кыдырова, 13
✗ Не найдено: Детский сад "Бала шак" | ул. Акбата, 68
✗ Не найдено: Детский сад "Сарқыт-А" | ул. Болатхан Тайжан, 29
✗ Не найдено: Детский сад "Ақ-Аянұр" | ул. Ибрая Жакаева, 85
✗ Не найдено: Детский сад "Баттыл" | ул. Қарлығаш, 7
✗ Не найдено: Детский сад "Ади" | ул. Даулеткерей, 25
✗ Не найдено: Детский сад " Радуга" | ул. Таргап, 11
✗ Не найдено: Детский сад "Жануя" | ул. Бекешева, 4
✗ Не найдено: Детский сад "Адеми" | ул. Луганского, 151
✗ Не найдено: Детский сад "Балбөбек" | Территория СТ Жетысу, 39
✗ Не найдено: Детский сад "Батыр Ел" | ул. Верненская, 73
✗ Не найдено: Детский сад "Ботақан" | ул. Есенберлина, 155
✗ Не найдено: Детский сад "Панда" | ул. Орманова, 32 А
✗ Не найдено: Детский сад "Нұр-Айбек" | Улица Каркаралы, 27а
✗ Не найдено: Детский сад "Талант" | ул. Митина, 23А
✗ Не найдено: Детский сад «Эльсана» | ул. Зверева, 28
✗ Не найдено: Детский сад "АлдиАмир | ул. Сырмак, 44А
✗ Не найдено: Детский сад "Аликош" | ул. Домбыра, 28
✗ Не найдено: Детский сад "Бэби Сад" | ул. Каирбекова, 37
✗ Не найдено: Детский сад "Умняшка" | ул. Ибрагимова, 105
✗ Не найдено: Детский сад "Алина" | ул. Сахариева, 11
✗ Не найдено: Детский сад "Дана Бала" | ул. Текемет, 40а
✗ Не найдено: Детский сад "АДИНА-Д" | ул. Табигат, 1
✗ Не найдено: Детский сад "Мадина -27" | ул. Молодежная, 69А
✗ Не найдено: Детский сад "Дария 23" | ул. Пестковского, 54
✗ Не найдено: Детский сад "Тедди" | ул. Венецианова, 21А
✗ Не найдено: Детский сад "Умит Ай" | мкр. Кокжиек, 7а
✗ Не найдено: Детский сад "Аиша" | ул. Саялы, 14
✗ Не найдено: Детский сад "Ай-Лау" | ул. Фаворского, 12
✗ Не найдено: Детский сад "БӨПЕШІМ" | ул. Парковая, 2
✗ Не найдено: Детский сад «Даниал» | ул. Куратова, 58
✗ Не найдено: Детский сад «Мечта» | ул. Минина, 24
✗ Не найдено: Детский сад "Балашым" | ул. Попова, 27
✗ Не найдено: Детский сад "ЛИДЕР" | мкр. Орбита 4, 25б
✗ Не найдено: Детский сад "Бэбисити 3" | ул. Кекилбайулы, 45
✗ Не найдено: Детский сад "Болашак" | пр. Сейфуллина, 544
✗ Не найдено: Детский сад "Балажан" | ул. Жандосова, 14
✗ Не найдено: Детский сад "Симба Kids" | ул. Кекилбайулы, 32А
✗ Не найдено: Детский сад "Мидас" | ул. Журавлева, 22
✗ Не найдено: Детский сад "Кулагер" | мкр. Казахфильм, 45
✗ Не найдено: Детский сад "Алгабас-3 | ул. Озтюрка, 5А
✗ Не найдено: Детский сад "Ахмадиева" | ул. Подгорная, 25/2
✗ Не найдено: Детский сад "Альтар" | ул. Булбул, 8/2
✗ Не найдено: Детский сад "Айару" | ул. Попова, 22
✗ Не найдено: Детский сад "Аль-Фараби" | ул. Рафика Нуртазина, 79
✗ Не найдено: Детский сад "Эрудиты" | ул. 20 линия, 62
✗ Не найдено: Детский сад "Уайз Кидс" | ул. Кольсай, 31
✗ Не найдено: Детский сад "Бэби_клуб" | мкр. Мамыр-7, 8/4
✗ Не найдено: Детский сад "Умка Сад" | мкр. Мамыр-4, 166
✗ Не найдено: Детский сад "Жан Бөпе - 1" | ул. Щепеткова, 113/3
✗ Не найдено: Детский сад "МЕГА КИДС" | ул. Садовникова, 35
✗ Не найдено: Детский сад "Нурислам" | мкр. Мамыр-4, 212
✗ Не найдено: Детский сад "Лаяна К" | ул. Бутина, 5
✗ Не найдено: Детский сад "Талант" | мкр. Атамекен, 245
✗ Не найдено: Детский сад "Асем-гул" | мкр. Мамыр-4, 205
✗ Не найдено: Детский сад "Ар-Дана" | ул. Нурмаханова, 30
✗ Не найдено: Детский сад "АЙ-БАЛА" | ул. Садовникова, 61
✗ Не найдено: Детский сад "Айсана" | мкр. Алмас, 134
✗ Не найдено: Детский сад "Қарлығаш" | мкр. Алтын Бесик, 168
✗ Не найдено: Детский сад "Нұр Сәби" | мкр. Аксай 1А, 10в
✗ Не найдено: Детский сад "Білім" | мкр. Мамыр 4, 4б
✗ Не найдено: Детский сад "Дамодара" | ул. Садовникова, 186
✗ Не найдено: Детский сад "Ару kids" | мкр. Алмас, 201
✗ Не найдено: Детский сад "СТУПЕНЬКИ" | мкр. Аксай-2, 70А
✗ Не найдено: Детский сад "АЛИМ" | мкр. 2, 7А
✗ Не найдено: Детский сад "Қонжықтар" | ул. Римова, 11
✗ Не найдено: Детский сад "ШамШер" | мкр. Мамыр 4, 128
✗ Не найдено: Детский сад "Бэйби-Ленд" | ул. Ыкылас, 26/1
✗ Не найдено: Детский сад "ЕЛАМАН"" | мкр. Баянаул, 56
✗ Не найдено: Детский сад "Сакобай" | ул. Трудовая, 58
✗ Не найдено: Детский сад "Садок ltd" | мкр. Алмас, 172
✗ Не найдено: Детский сад "Айсәт" | ул. Әнет баба, 37
✗ Не найдено: Детский сад "Жан -Дария" | ул. Акшагыл, 23
✗ Не найдено: Детский сад "Адилек" | ул. Аханова, 58
✗ Не найдено: Детский сад "Қошақан" | ул. Наурызбаева, 35
✗ Не найдено: Детский сад "Ботақан" | ул. Центральная, 70/1
✗ Не найдено: Детский сад "Ақсұнқар" | ул. Игілік, 11
✗ Не найдено: Детский сад "Жеті Бата" | ул. Чойбалсана, 7
✗ Не найдено: Детский сад "Балауса" | ул. Ахметова, 30
✗ Не найдено: Детский сад "Аян-Ай" | ул. Жидели, 42
✗ Не найдено: Детский сад "С. Ақерке" | ул. Еспаева, 80/1
✗ Не найдено: Детский сад "Биғайша" | ул. Бекболата, 29/1
✗ Не найдено: Детский сад "Жан бөпе" | ул. Еспаев, 80
✗ Не найдено: Детский сад "ИБОСИК" | ул. Байтенова, 102
✗ Не найдено: Детский сад "Арман" | мкр. Мадениет, 288/30
✗ Не найдено: Детский сад "Ашамай" | ул. Ушкын, 17
✗ Не найдено: Детский сад «Ақбота К» | ул. Фаризы Онгарсыновой, 78
✗ Не найдено: Детский сад "Ақ-Патша" | ул. Мамбетова, 150
✗ Не найдено: Детский сад "Тұмар-А" | Квартал Жаңа құрылыс, 211
✗ Не найдено: Детский сад "АЙГОЛЕК" | ул. Балкудык, 6/1
✗ Не найдено: Детский сад «Бакуня» | ул. Центральная, 165
✗ Не найдено: Детский сад "Лаяна" | ул. Койтас, 17
✗ Не найдено: Детский сад "Оспан 05" | ул. Жапсарбаева, 45
✗ Не найдено: Детский сад "ОЦ "Аяна" | ул. Талдыарал, 12а
✗ Не найдено: Детский сад "Амирхан-А" | ул. Федченко, 17
✗ Не найдено: Детский сад «Родничок» | ул. Аптечная, 22
✗ Не найдено: Детский сад "Айто-К" | ул. Балтабай, 74
✗ Не найдено: Детский сад «i.Сәби» | ул. Бегазы, 1в
✗ Не найдено: Детский сад "Күнбағыс" | ул. Магистральная, 17
✗ Не найдено: Детский сад «Акбопе» | Мамытов көш., 94/13
✗ Не найдено: Детский сад "Жас сұңқар" | ул. Центральная, 1/23
✗ Не найдено: детский сад "Адина" | ул. Тауасарова, 68
✗ Не найдено: ТОО детский сад "АдиРай" | ул. Алпамыс, 125/1
✗ Не найдено: детский сад "Самұрық" | ул. Касыма Шарипова, 83
✗ Не найдено: ТОО "Детский сад Алан" | ул. Мамытова, 65
✗ Не найдено: ТОО "НҰҚ" детский сад "Бақ" | ул. Утемисова, 111
✗ Не найдено: ТОО "Детский сад Хан" | ул. Розыбакиева, 9
✗ Не найдено: АО детский сад "Бахус" | ул. Карасай Батыра, 175
✗ Не найдено: Детский сад "Хан-Тәңірі-7" | ул. Василия Бенберина, 38/1
✗ Не найдено: Детский сад "ErnarRai" | ул. Шакшак Жанибека, 45/1
✗ Не найдено: ТОО "BAL-bala 1 балабақшасы" | ул. Туймебаева, 39
✗ Не найдено: ТОО детский сад "Құралай Кидс" | ул. Доспанова, 20
✗ Не найдено: Ясли-сад "Еркем-Ай" | ул. Жамакаева, 93
✗ Не найдено: Ясли-сад "Зердеш-3" | ул. Болтириковой, 50
✗ Не найдено: Детский сад "BAQ JAN" | 22-я улица, 34
✗ Не найдено: Детский сад "Алем" | ул. Нурлы тан, 17
✗ Не найдено: Детский сад "Зейн" | ул. Сейдилда, 5
✗ Не найдено: Детский сад "Er-Asul" | ул. Жунисова, 73
✗ Не найдено: Детский сад "AzaleaM" | ул. Герольда Бельгера, 55
✗ Не найдено: Детский сад "Rauan" | ул. 7 линия, 103
✗ Не найдено: Детский сад "Ұлан" | ул. Дархан, 36
✗ Не найдено: Детский сад "ALATAU" | ул. Афцинао, 11
✗ Не найдено: Детский сад "SymLynn" | ул. Затаевича, 77
✗ Не найдено: Детский сад "Koktobe" | ул. Найманбаева, 95
✗ Не найдено: Детский сад "My kid" | ул. Аманжола, 54
✗ Не найдено: Детский сад "Alishka" | ул. Янушкевича, 49
✗ Не найдено: Детский сад "Rani" | ул. Жиренше, 75а
✗ Не найдено: Детский сад "StArt" | ул. Кармысова, 90
✗ Не найдено: Детский сад "KULPASH" | ул. Жуковского, 7
✗ Не найдено: Детский сад «Aqbesik»" | ул. Клубная, 24
✗ Не найдено: Детский сад "Alina" | ул. Каирбекова, 68
✗ Не найдено: Детский сад "GRAMMY" | ул. Жамакаева, 46
✗ Не найдено: Детский сад "Ai-bota" | ул. Аныракай, 6
✗ Не найдено: Детский сад «Bambi» | мкр. Айнабулак-4, 167а
✗ Не найдено: Детский сад "KIS" | пр. Аль-Фараби, 118/15
✗ Не найдено: Детский сад "УМКА" | ул. Си Синхая, 1
✗ Не найдено: Детский сад «ЭЛКО» | мкр. Орбита 3, 8а
✗ Не найдено: Детский сад "Mykid2" | 6-я улица, 25
✗ Не найдено: Детский сад "Умка" | ул. Киргизская, 2
✗ Не найдено: Детский сад "QazBaby" | ул. Бұлбұл, 17
✗ Не найдено: Детский сад "Нэмо" | мкр. Атамекен, 163А
✗ Не найдено: Детский сад "ZERDESH" | мкр. Атамекен, 113
✗ Не найдено: Детский сад "Ar Kids" | мкр. Мамыр-4, 117/7
✗ Не найдено: Детский сад "iBópe" | мкр. Баянаул, 8
✗ Не найдено: Детский сад "ҚОНЖЫҚ" | мкр. Мамыр 4, 148 А
✗ Не найдено: Детский сад "УМКА" | мкр. Мамыр-4, 57А
✗ Не найдено: Детский сад "ЛОЛО" | мкр. Атамекен, 123
✗ Не найдено: Детский сад "KARSHAL" | мкр. Атамекен, 33
✗ Не найдено: Детский сад "Zere" | мкр. 3, 72
✗ Не найдено: Детский сад "Дияр" | ул. Акжунис, 9а
✗ Не найдено: Детский сад "ДИАР" | 2-й мкр., 40Г
✗ Не найдено: Детский сад "Үкі" | ул. Жалантос Бахадур, 47
✗ Не найдено: Детский-сад "Аяла" | ул. Аркалык, 52А
✗ Не найдено: Детский сад "Арша" | ул. Тауелсиздик, 1
✗ Не найдено: Детский сад "Erketai" | ул. Талбесик, 65
✗ Не найдено: Детский сад "Айша" | ул. Ақтілек, 8
✗ Не найдено: Детский сад «Азя» | ул. Байтенева, 129
✗ Не найдено: Детский сад "АҚҚУ" | ул. Черемушки 2, 15а
✗ Не найдено: Детский сад "Мәржол" | ул. Арқалық, 68
✗ Не найдено: Детский сад "Ledi Di" | ул. Османова, 1Д
✗ Не найдено: Детский сад "BoBo"" | ул. Акшагыл, 28/3
✗ Не найдено: детский сад "AIZARA" | ул. Байдібек би, 134
✗ Не найдено: ТОО детский сад "NAZ" | ул. Тойшыбек Батыр, 68
✗ Не найдено: детский сад "Sanya" | ул. Жетысу квартал, 58
✗ Не найдено: ТОО детский сад "Сержан- К" | ул. Аркалык, 6/1
✗ Не найдено: ТОО детский сад "BB DAmir" | ул. Асанова, 7

Осталось дупликатов: 279
Не найдено координат: 273

In [33]:
import pandas as pd
import requests
import time
import re

df = pd.read_csv("kindergartens_almaty_private_osm_matched_final.csv")

def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15

# --- Nominatim ---
def nominatim_geocode(q):
    try:
        r = requests.get(
            "https://nominatim.openstreetmap.org/search",
            params={"q": q, "format": "json", "limit": 3,
                    "countrycodes": "kz", "addressdetails": 0},
            headers={"User-Agent": "almaty-dedup/1.0"},
            timeout=10
        )
        for res in r.json():
            lat, lon = float(res["lat"]), float(res["lon"])
            if in_bbox(lat, lon):
                return lat, lon
    except:
        pass
    return None, None

# --- 2GIS ---
def twogis_geocode(addr):
    try:
        r = requests.get(
            "https://geocode.maps.co/search",  # или можно попробовать другой
            params={"q": f"{addr}, Алматы", "format": "json"},
            timeout=10
        )
        for res in r.json():
            lat, lon = float(res["lat"]), float(res["lon"])
            if in_bbox(lat, lon):
                return lat, lon
    except:
        pass
    return None, None

# --- Очистка адреса ---
def clean_variants(addr):
    if pd.isna(addr):
        return []
    s = str(addr).strip()
    
    variants = []
    
    # Оригинал + город
    variants.append(f"{s}, Алматы, Казахстан")
    
    # Нормализация сокращений
    s2 = s.replace("мкр.", "микрорайон").replace("ул.", "улица") \
          .replace("пр.", "проспект").replace("пр-т", "проспект") \
          .replace("пер.", "переулок")
    variants.append(f"{s2}, Алматы")
    
    # Убрать микрорайон — оставить только улицу/дом
    s3 = re.sub(r"микрорайон\s+\S+,?\s*", "", s2, flags=re.IGNORECASE).strip(" ,")
    if s3 and s3 != s2:
        variants.append(f"{s3}, Алматы")
    
    # Только цифры из адреса (дом) + улица без дома
    m = re.match(r"(.+?),?\s*(\d+\w?)$", s2)
    if m:
        street = m.group(1).strip()
        variants.append(f"{street}, Алматы")
    
    return list(dict.fromkeys(v for v in variants if v.strip()))

# Строки с NaN координатами
to_fix = df[df["lat"].isna()].index.tolist()
print(f"Всего для геокодирования: {len(to_fix)}")

found = 0
for i in to_fix:
    addr = df.loc[i, "address"]
    name = df.loc[i, "name"]
    resolved = False
    
    for variant in clean_variants(addr):
        # 1. Nominatim
        lat, lon = nominatim_geocode(variant)
        if lat:
            df.loc[i, "lat"] = lat
            df.loc[i, "lon"] = lon
            df.loc[i, "method"] = "nominatim_dedup"
            print(f"✓ NOM  {name[:40]} | {variant[:50]}")
            resolved = True
            found += 1
            break
        time.sleep(1.1)  # Nominatim rate limit: 1 req/sec
    
    if not resolved:
        print(f"✗      {name[:40]} | {addr}")

print(f"\nНайдено: {found}/{len(to_fix)}")
print(f"Осталось NaN: {df['lat'].isna().sum()}")
print(f"Дупликатов: {df.duplicated(subset=['lat','lon']).sum()}")

df.to_csv("kindergartens_almaty_private_osm_matched_final.csv", index=False)

Всего для геокодирования: 273
✓ NOM  Детский сад "Аиша" | ул. Саялы, 14, Алматы, Казахстан
✓ NOM  Детский сад "Мимишка" | ул. Димитрова, 10, Алматы, Казахстан
✓ NOM  Детский сад «Гусельки» | ул. Степана Разина, 94, Алматы, Казахстан
✓ NOM  Детский сад "КҮН ШУАҚ" | ул. Дунентаева, 6/4, Алматы, Казахстан
✗      Детский сад "АЗИМКА" | ул. Дегдара, 36/1
✓ NOM  Детский сад "Тимошка" | улица Толегена Тажибаева, Алматы
✓ NOM  Детский сад "Жансая-Сәт" | ул. Зимняя, 18Б, Алматы, Казахстан
✓ NOM  Детский сад «Карусель» | ул. Стахановская, 19, Алматы, Казахстан
✓ NOM  Детский сад "Куанар" | улица Топчиева, Алматы
✓ NOM  Детский сад "Биржан К" | ул. Зимняя, 2, Алматы, Казахстан
✓ NOM  Детский сад "Адель&F" | проспект Суюнбая, 661, Алматы
✓ NOM  Детский сад "Кокетай" | ул. Дунентаева, 8/1, Алматы, Казахстан
✓ NOM  Детский сад «АкЕрке" | улица Белбулак, Алматы
✓ NOM  Детский сад "Балдаурен" | ул. Ижевская, 33, Алматы, Казахстан
✓ NOM  Детский сад "Кошахан" | 22-я улица, 46, Алматы, Казахстан
✓ NOM  Детский сад "Бақ - Бала" | ул. Баймагамбетова, 82/4, Алматы, Казахстан
✓ NOM  Детский сад "3 Кита" | ул. Щелково, 1, Алматы, Казахстан
✓ NOM  Детский ясли-сад "Еркетай" | ул. Соболева, 164, Алматы, Казахстан
✓ NOM  Детский сад "АЙЗЕРЕ и К" | ул. Казангап, 21, Алматы, Казахстан
✓ NOM  Детский сад "Аврора" | ул. Глинки, 4, Алматы, Казахстан
✓ NOM  Детский сад «Малышарики» | 4-я улица, 10, Алматы, Казахстан
✓ NOM  Детский сад "BAQ JAN" | 22-я улица, 34, Алматы, Казахстан
✓ NOM  Детский сад "Аяу-Нұр" | 15-я улица, Алматы
✓ NOM  Детский сад "Береке - Мармар" | ул. Береке, 40, Алматы, Казахстан
✓ NOM  Детский сад "Алем" | ул. Нурлы тан, 17, Алматы, Казахстан
✓ NOM  Детский сад "Шапағат" | ул. Таргап, 117, Алматы, Казахстан
✓ NOM  Детский сад "Munarat Almaty" | ул. Аширбек Сыгай, 96, Алматы, Казахстан
✓ NOM  Детский сад "Нұрбала" | ул. Телжан Шонанулы, 78, Алматы, Казахстан
✗      Детский центр "Kinder land" | ул. Ш. Айтматова, 71
✓ NOM  Детский сад «Алихан» | ул. Нурпеисова, 204, Алматы, Казахстан
✓ NOM  Детский сад "Сары Балапан" | ул. Тажибаева, 46, Алматы, Казахстан
✓ NOM  Детский сад "Зейн" | ул. Сейдилда, 5, Алматы, Казахстан
✗      Детский сад "Top Kids 2" | ул. Кенжетаев, 119
✓ NOM  Детский сад "Аңсаған-К" | ул. Ашимова, 343/2, Алматы, Казахстан
✓ NOM  Детский сад "Er-Asul" | ул. Жунисова, 73, Алматы, Казахстан
✓ NOM  Детский сад "Би- Тұмар" | ул. Камысдала, 27, Алматы, Казахстан
✓ NOM  Детский сад "CӘТ-БЕРЕКЕ" | ул. Жунисова, 134/80, Алматы, Казахстан
✗      Детский сад "Top Kids" | ул. Кенжетаев, 121
✓ NOM  Детский сад "SUNSHINE 2" | ул. Актамберды жырау, 3, Алматы, Казахстан
✓ NOM  Детский сад "AzaleaM" | ул. Герольда Бельгера, 55, Алматы, Казахстан
✓ NOM  Детский сад "Муслимхан" | ул. Аширбек Сыгай, 47, Алматы, Казахстан
✓ NOM  Детский сад "Rauan" | ул. 7 линия, 103, Алматы, Казахстан
✓ NOM  Детский сад "Айымсұлу" | ул. Сагдиева, 63, Алматы, Казахстан
✓ NOM  Детский сад "Ұлан" | ул. Дархан, 36, Алматы, Казахстан
✓ NOM  Детский сад "Радуга 2" | ул. Таргап, 109, Алматы, Казахстан
✓ NOM  Детский сад "Бала-Дария" | ул. Айбергенова, 92, Алматы, Казахстан
✓ NOM  Детский сад "Актыным" | ул. Жунисова, 53, Алматы, Казахстан
✓ NOM  Детский сад "Сұңқар" | ул. Айбергенова, 92, Алматы, Казахстан
✓ NOM  Детский сад "Нұр Дария" | ул. Айбергенова, 45, Алматы, Казахстан
✓ NOM  Детский сад "Айдария" | ул. Сагдиев, 59, Алматы, Казахстан
✗      Детский сад "Тамирис" | ул. Кенесары-Хан, 116
✗      Детский сад "Талшын" | ул. Сейитбекова, 43
✗      Детский сад «Бала- Дария» филиал | ул. Аширбек Сыгай, 55
✗      Детский сад "Асылым" | ул. Ашимова, 259
✗      Детский сад "АЯНАТ" | ул. Аскарова, 28
✗      Детский сад "Дария Айша" | ул. Қыдырбеков, 60/1
✗      Детский сад "ALATAU" | ул. Афцинао, 11
✗      Детский сад "MARY POPPINS" | ул. Кали-Надырова, 98/1
✗      Детский сад "ЛИМПОПО" | ул. Аширбек Сыгай, 71
✗      Детский сад "БАТЫР-ШИФА" | ул. Кали Надырова, 4
✗      Детский сад "Балапан" | ул. Жалкамыс, 1
✗      Детский сад "Нұрбөпе" | ул. Герольда Бельгера, 57/1
✗      Детский сад "Ерсинтай" | ул. Аспандиярова, 83
✗      Детский сад "ЖАСДИМЕЙР" | ул. Кыдырова, 13
✗      Детский сад "Кенгуренок-А" | ул. Сейтметова, 87
✗      Детский сад "Бала шак" | ул. Акбата, 68
✗      Детский сад "Сарқыт-А" | ул. Болатхан Тайжан, 29
✗      Детский сад "Ақ-Аянұр" | ул. Ибрая Жакаева, 85
✗      Детский сад "Баттыл" | ул. Қарлығаш, 7
✗      Детский сад «АЙГОЛЕК-1» | ул. Сейтметов, 102
✗      Детский сад "Ади" | ул. Даулеткерей, 25
✗      Детский сад "Bаmbino" | ул. Кыдырбекова, 60/1
✗      Детский сад " Радуга" | ул. Таргап, 11
✗      Детский сад "Жануя" | ул. Бекешева, 4
✗      Детский сад "Адеми" | ул. Луганского, 151
✗      Детский сад "SymLynn" | ул. Затаевича, 77
✗      Детский сад "Koktobe" | ул. Найманбаева, 95
✗      Детский сад "Балбөбек" | Территория СТ Жетысу, 39
✗      Детский сад "Батыр Ел" | ул. Верненская, 73
✗      Детский сад "Ботақан" | ул. Есенберлина, 155
✗      Детский сад "My kid" | ул. Аманжола, 54
✗      Детский сад "Alishka" | ул. Янушкевича, 49
✗      Детский сад "Панда" | ул. Орманова, 32 А
✗      Детский сад "Rani" | ул. Жиренше, 75а
✗      Детский сад "ErnarRai" | ул. Шакшак Жанибека, 45/1
✗      Детский сад "Нұр-Айбек" | Улица Каркаралы, 27а
✗      Детский сад "Талант" | ул. Митина, 23А
✗      Ясли-сад "Еркем-Ай" | ул. Жамакаева, 93
✗      Детский сад "Еркетай" | ул. Каркаралы, 23а
✗      Детский сад «Эльсана» | ул. Зверева, 28
✗      Детский сад "StArt" | ул. Кармысова, 90
✗      Детский сад "KULPASH" | ул. Жуковского, 7
✗      Детский сад "АлдиАмир | ул. Сырмак, 44А
✗      Детский сад "Аликош" | ул. Домбыра, 28
✗      Детский сад «Aqbesik»" | ул. Клубная, 24
✗      Детский сад "Бэби Сад" | ул. Каирбекова, 37
✗      Детский сад "Березка" | ул. Рубинштейна, 3а
✗      Детский сад "Alina" | ул. Каирбекова, 68
✗      Детский сад "Умняшка" | ул. Ибрагимова, 105
✗      Детский сад "Алина" | ул. Сахариева, 11
✗      Детский сад "Дана Бала" | ул. Текемет, 40а
✗      Детский сад "BabyBoom 3" | ул. Поповича, 45
✗      Детский сад "GRAMMY" | ул. Жамакаева, 46
✗      Детский сад "TILVALDY" | ул. Нурмагамбетова, 202
✗      Детский сад "Ai-bota" | ул. Аныракай, 6
✗      Детский сад «Bambi» | мкр. Айнабулак-4, 167а
✗      Детский сад "Львёнок" | ул. Жансугуров, 250
✗      Детский сад "АДИНА-Д" | ул. Табигат, 1
✗      Детский сад "Мадина -27" | ул. Молодежная, 69А
✗      Детский сад "Дария 23" | ул. Пестковского, 54
✗      Детский сад "Тедди" | ул. Венецианова, 21А
✗      Детский сад "Умит Ай" | мкр. Кокжиек, 7а
✗      Детский сад "Аиша" | ул. Саялы, 14
✗      Детский сад "Ай-Лау" | ул. Фаворского, 12
✗      Детский сад "БӨПЕШІМ" | ул. Парковая, 2
✗      Детский сад «Даниал» | ул. Куратова, 58
✗      Детский сад "Қарлығаш1" | ул. Грушовая, 12а
✗      Детский сад «Мечта» | ул. Минина, 24
✗      Детский сад "KIS" | пр. Аль-Фараби, 118/15
✗      Детский сад "Балашым" | ул. Попова, 27
✗      Детский сад "ЛИДЕР" | мкр. Орбита 4, 25б
✗      Детский сад "Бэбисити 3" | ул. Кекилбайулы, 45
✗      Детский сад "Tarlan kids" | ул. Кенесары хан, 67
✗      Детский сад "УМКА" | ул. Си Синхая, 1
✗      Детский сад "Болашак" | пр. Сейфуллина, 544
✗      Детский сад "Балажан" | ул. Жандосова, 14
✗      Детский сад "Р-Мурагер 2" | ул. Санаторная, 12
✗      Детский сад «ЭЛКО» | мкр. Орбита 3, 8а
✗      Детский сад "Зайка" | ул. Маркова, 9
✗      Детский сад "Симба Kids" | ул. Кекилбайулы, 32А
✗      Детский сад "Мидас" | ул. Журавлева, 22
✗      Детский сад "Кулагер" | мкр. Казахфильм, 45
✗      Детский сад "Алгабас-3 | ул. Озтюрка, 5А
✗      Филиал "Образовательного комплекса школы | мкр. Мирас, 59
✗      Детский сад "Ахмадиева" | ул. Подгорная, 25/2
✗      Детский сад "Альтар" | ул. Булбул, 8/2
✗      Детский сад "Айару" | ул. Попова, 22
✗      Ясли-сад "Зердеш-3" | ул. Болтириковой, 50
✗      Детский сад "МЕГА КИДС" (филиал) | 11-я улица, 8
✗      Детский сад "Mykid2" | 6-я улица, 25
✗      Детский сад "Аль-Фараби" | ул. Рафика Нуртазина, 79
✗      Детский сад «Sparks Preschool» | мкр. Мирас, 160
✗      Детский сад "Эрудиты" | ул. 20 линия, 62
✗      Детский сад "Умка" | ул. Киргизская, 2
✗      Детский сад "Уайз Кидс" | ул. Кольсай, 31
✗      Детский сад "QazBaby" | ул. Бұлбұл, 17
✗      Детский сад "Бэби_клуб" | мкр. Мамыр-7, 8/4
✗      Детский садик "Чебурашка" | мкр. Алтын бесик, 177
✓ NOM  Детский сад "Умка Сад" | микрорайон Мамыр-4, Алматы
✓ NOM  Детский сад "Жан Бөпе - 1" | ул. Щепеткова, 113/3, Алматы, Казахстан
✓ NOM  Детский сад "МЕГА КИДС" | ул. Садовникова, 35, Алматы, Казахстан
✓ NOM  Детский сад "АҚӘЛЕМ 2" | ул. Пролетарская, 15, Алматы, Казахстан
✓ NOM  Детский сад "Нэмо" | микрорайон Атамекен, 163А, Алматы
✓ NOM  Детский сад "Нурислам" | микрорайон Мамыр-4, 212, Алматы
✓ NOM  Детский сад "ZERDESH" | микрорайон Атамекен, 113, Алматы
✓ NOM  Детский сад "Kun ai" | ул. Шаймерденова, 27/33, Алматы, Казахстан
✓ NOM  Детский сад "Лаяна К" | ул. Бутина, 5, Алматы, Казахстан
✗      Детский сад "Асемгул-1" | мкр. Алтын Бесик, 53
✓ NOM  Детский сад "Ar Kids" | микрорайон Мамыр-4, 117/7, Алматы
✓ NOM  Мини-центр "ДиДи2016" (филиал) | микрорайон Мамыр-7, 8/1, Алматы
✓ NOM  Детский сад "Талант" | микрорайон Атамекен, 245, Алматы
✓ NOM  Детский сад "Асем-гул" | микрорайон Мамыр-4, 205, Алматы
✓ NOM  Детский-ясли сад "Береке - 2020" | микрорайон Атамекен, 33/1, Алматы
✓ NOM  Детский сад "iBópe" | микрорайон Баянаул, 8, Алматы
✓ NOM  Детский сад "Ар-Дана" | ул. Нурмаханова, 30, Алматы, Казахстан
✓ NOM  Детский сад "Эврика" | микрорайон Мамыр 4, Алматы
✓ NOM  Детский сад "Antaress kids-2" | микрорайон Алмас, 106, Алматы
✓ NOM  Детский сад "ҚОНЖЫҚ" | микрорайон Мамыр 4, 148 А, Алматы
✓ NOM  Детский сад "УМКА" | 57А, Алматы
✓ NOM  Детский сад "АЙ-БАЛА" | ул. Садовникова, 61, Алматы, Казахстан
✓ NOM  Детский сад "ЛОЛО" | микрорайон Атамекен, 123, Алматы
✓ NOM  Детский сад "KARSHAL" | микрорайон Атамекен, 33, Алматы
✓ NOM  Детский сад "Айсана" | микрорайон Алмас, 134, Алматы
✓ NOM  Детский сад "Zere" | микрорайон 3, 72, Алматы
✗      Детский сад "Қарлығаш" | мкр. Алтын Бесик, 168
✓ NOM  Образовательный центр "Арайлым" | микрорайон Баянаул, 40, Алматы
✓ NOM  Детский сад "Нұр Сәби" | микрорайон Аксай 1А, 10в, Алматы
✗      Детский сад «Еркежан» | мкр. Алтын бесік, 223
✓ NOM  Детский сад "Білім" | микрорайон Мамыр 4, Алматы
✓ NOM  Ақниет Образовательный Центр | микрорайон Мамыр 4, 58, Алматы
✓ NOM  Детский сад "Дамодара" | ул. Садовникова, 186, Алматы, Казахстан
✓ NOM  Детский сад "i.Bala 2" | микрорайон Мамыр 4, 18, Алматы
✓ NOM  Детский Центр "Умка" | 3а, 85, Алматы
✓ NOM  Детский сад "Alina-kids-1" | микрорайон Мамыр-4, 210, Алматы
✓ NOM  Детский сад "Ару kids" | микрорайон Алмас, 201, Алматы
✓ NOM  Детский сад "Зере " | 70Б, Алматы
✓ NOM  Детский сад "Дияр" | ул. Акжунис, 9а, Алматы, Казахстан
✓ NOM  Детский сад "СТУПЕНЬКИ" | микрорайон Аксай-2, 70А, Алматы
✓ NOM  Детский сад "АЛИМ" | микрорайон 2, 7А, Алматы
✗      Детский сад "Қонжықтар" | ул. Римова, 11
✓ NOM  Детский сад "ШамШер" | микрорайон Мамыр 4, 128, Алматы
✓ NOM  Детский сад "Бэйби-Ленд" | ул. Ыкылас, 26/1, Алматы, Казахстан
✓ NOM  Детский сад "ЕЛАМАН"" | микрорайон Баянаул, 56, Алматы
✓ NOM  Детский сад "Сакобай" | ул. Трудовая, 58, Алматы, Казахстан
✓ NOM  Детский сад " ТОЦ Өнер " | ул. Мухамеджанова, 42, Алматы, Казахстан
✓ NOM  Детский сад "Садок ltd" | микрорайон Алмас, 172, Алматы
✓ NOM  Мини-центр "АйДиНур" | микрорайон Мамыр 4, 156, Алматы
✓ NOM  Детский сад "ДИАР" | 2-й микрорайон, Алматы
✗      Детский сад "Айсәт" | ул. Әнет баба, 37
✗      Детский сад "Жан -Дария" | ул. Акшагыл, 23
✓ NOM  Образовательный центр "Алладин" | улица Кокшокы, Алматы
✓ NOM  Детский сад "Адилек" | ул. Аханова, 58, Алматы, Казахстан
✓ NOM  Детский сад "Қошақан" | ул. Наурызбаева, 35, Алматы, Казахстан
✓ NOM  Детский сад "Ботақан" | ул. Центральная, 70/1, Алматы, Казахстан
✗      Детский сад "Ақсұнқар" | ул. Игілік, 11
✗      Детский сад "Ертарғын" | ул. Арқалық, 19/6
✗      Детский сад "Хан-Тәңірі-7" | ул. Василия Бенберина, 38/1
✓ NOM  Детский сад "Жеті Бата" | ул. Чойбалсана, 7, Алматы, Казахстан
✗      Детский сад "Бексұлтан 7" | ул. Кокжайлау, 7
✓ NOM  Детский сад "Үкі" | ул. Жалантос Бахадур, 47, Алматы, Казахстан
✓ NOM  Детский сад "Балауса" | ул. Ахметова, 30, Алматы, Казахстан
✓ NOM  Детский сад "Роза" | ул. Аубакирова, 118, Алматы, Казахстан
✗      Детский сад "Нұр-Сәт1" | ул. Абылай хан, 10
✗      Детский-сад "Аяла" | ул. Аркалык, 52А
✓ NOM  Детский сад "Аян-Ай" | ул. Жидели, 42, Алматы, Казахстан
✓ NOM  Детский сад "Мерей компани" | ул. Текес, 67, Алматы, Казахстан
✗      Детский сад "Молдир-2" | ул. Жанкожа батыр, 73
✓ NOM  Детский сад "С. Ақерке" | ул. Еспаева, 80/1, Алматы, Казахстан
✓ NOM  Детский сад "Ерке" | ул. Ахметова, 57, Алматы, Казахстан
✓ NOM  Детский сад "Биғайша" | ул. Бекболата, 29/1, Алматы, Казахстан
✓ NOM  Детский сад "Жан бөпе" | ул. Еспаев, 80, Алматы, Казахстан
✓ NOM  Детский сад "ERKETAI-2" | ул. Талбесик, 32, Алматы, Казахстан
✓ NOM  Детский сад "ИБОСИК" | ул. Байтенова, 102, Алматы, Казахстан
✓ NOM  Детский сад "Арша" | ул. Тауелсиздик, 1, Алматы, Казахстан
✓ NOM  Детский сад "Арман" | 288/30, Алматы
✓ NOM  Детский сад "Ашамай" | ул. Ушкын, 17, Алматы, Казахстан
✓ NOM  Детский сад "Erketai" | ул. Талбесик, 65, Алматы, Казахстан
✓ NOM  Детский сад "Зерде-2" | ул. Тайконыр, 41, Алматы, Казахстан
✓ NOM  Детский сад «Ақбота К» | ул. Фаризы Онгарсыновой, 78, Алматы, Казахстан
✓ NOM  Детский сад "Ақ-Патша" | ул. Мамбетова, 150, Алматы, Казахстан
✗      Детский сад "Тұмар-А" | Квартал Жаңа құрылыс, 211
✓ NOM  Детский сад «Ертөстік» | ул. Доспановой, 26, Алматы, Казахстан
✓ NOM  Детский сад "Венера" | ул. Сапиева, 6, Алматы, Казахстан
✓ NOM  Детский сад "АЙГОЛЕК" | ул. Балкудык, 6/1, Алматы, Казахстан
✗      Детский сад "Айша" | ул. Ақтілек, 8
✗      Детский сад «Азя» | ул. Байтенева, 129
✓ NOM  Детский сад «Бакуня» | ул. Центральная, 165, Алматы, Казахстан
✓ NOM  Детский сад "Лаяна" | ул. Койтас, 17, Алматы, Казахстан
✓ NOM  Детский сад "Оспан 05" | ул. Жапсарбаева, 45, Алматы, Казахстан
✓ NOM  Детский сад "ОЦ "Аяна" | ул. Талдыарал, 12а, Алматы, Казахстан
✓ NOM  Детский сад "Нұр Болашақ" | ул. Онгарсыновой, 15, Алматы, Казахстан
✓ NOM  Детский сад "АҚҚУ" | улица Черемушки 2, Алматы
✓ NOM  Детский сад "Амирхан-А" | ул. Федченко, 17, Алматы, Казахстан
✗      Детский сад "Еркемай" | ул. Доспанова, 22
✓ NOM  Детский сад "Зерде" | ул. Тайконыр, 41, Алматы, Казахстан
✓ NOM  Детский сад «Родничок» | ул. Аптечная, 22, Алматы, Казахстан
✓ NOM  Детский сад "Айто-К" | ул. Балтабай, 74, Алматы, Казахстан
✗      Детский сад "Мәржол" | ул. Арқалық, 68
✓ NOM  Детский сад "Ledi Di" | ул. Османова, 1Д, Алматы, Казахстан
✓ NOM  Детский сад «i.Сәби» | ул. Бегазы, 1в, Алматы, Казахстан
✓ NOM  Детский сад "Күнбағыс" | ул. Магистральная, 17, Алматы, Казахстан
✗      Детский сад «Акбопе» | Мамытов көш., 94/13
✓ NOM  Детский сад "Жас сұңқар" | ул. Центральная, 1/23, Алматы, Казахстан
✓ NOM  детский сад "Адина" | ул. Тауасарова, 68, Алматы, Казахстан
✗      ТОО детский сад "Құралай Кидс" | ул. Доспанова, 20
✓ NOM  детский сад "Балдаурен" | ул. Айналмалы, 138, Алматы, Казахстан
✗      ТОО детский сад "АдиРай" | ул. Алпамыс, 125/1
✗      ТОО "Детский сад Бекося" | ул. Курти, 18
✗      ТОО детский сад "Хан-9" | ул. Аркалык, 25/1
✗      Детский сад "BoBo"" | ул. Акшагыл, 28/3
✗      детский сад "AIZARA" | ул. Байдібек би, 134
✓ NOM  ТОО "BAL-bala 1 балабақшасы" | ул. Туймебаева, 39, Алматы, Казахстан
✗      ТОО детский сад "NAZ" | ул. Тойшыбек Батыр, 68
✓ NOM  детский сад "Sanya" | ул. Жетысу квартал, 58, Алматы, Казахстан
✓ NOM  детский сад "Самұрық" | ул. Касыма Шарипова, 83, Алматы, Казахстан
✓ NOM  ТОО "Детский сад Алан" | ул. Мамытова, 65, Алматы, Казахстан
✓ NOM  ТОО "НҰҚ" детский сад "Бақ" | ул. Утемисова, 111, Алматы, Казахстан
✓ NOM  ТОО детский сад "Еркеназ 1" | ул. Туйемойнак, 47а, Алматы, Казахстан
✗      ТОО детский сад "Сержан- К" | ул. Аркалык, 6/1
✓ NOM  ТОО детский сад "BB DAmir" | ул. Асанова, 7, Алматы, Казахстан
✓ NOM  ТОО "Детский сад "Мың бала Алматы" | ул. Казтуган Жырау, 29/1, Алматы, Казахстан
✓ NOM  ТОО "Детский сад Хан" | ул. Розыбакиева, 9, Алматы, Казахстан
✓ NOM  АО детский сад "Бахус" | ул. Карасай Батыра, 175, Алматы, Казахстан

Найдено: 144/273
Осталось NaN: 129
Дупликатов: 163

In [35]:
import pandas as pd
import requests
import time
import re

df = pd.read_csv("kindergartens_almaty_private_osm_matched_final.csv")

def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15

# 2GIS неофициальный geocoder
def twogis_geocode(addr):
    try:
        r = requests.get(
            "https://catalog.api.2gis.com/3.0/items/geocode",
            params={
                "q": f"{addr}, Алматы",
                "fields": "items.point",
                "key": "rubimap",  # публичный демо-ключ
                "locale": "ru_KZ",
            },
            timeout=10
        )
        data = r.json()
        items = data.get("result", {}).get("items", [])
        for item in items:
            pt = item.get("point", {})
            lat, lon = pt.get("lat"), pt.get("lon")
            if lat and lon and in_bbox(lat, lon):
                return lat, lon
    except:
        pass
    return None, None

# Yandex geocoder (бесплатный лимит)
def yandex_geocode(addr):
    try:
        r = requests.get(
            "https://geocode-maps.yandex.ru/1.x/",
            params={
                "apikey": "демо",  # замените на свой ключ если есть
                "geocode": f"Алматы, {addr}",
                "format": "json",
                "ll": "76.89,43.24",
                "spn": "0.4,0.3",
                "rspn": 1,
                "results": 1,
            },
            timeout=10
        )
        coll = r.json()["response"]["GeoObjectCollection"]["featureMember"]
        if coll:
            pos = coll[0]["GeoObject"]["Point"]["pos"].split()
            lon, lat = float(pos[0]), float(pos[1])
            if in_bbox(lat, lon):
                return lat, lon
    except:
        pass
    return None, None

def clean_variants(addr):
    if pd.isna(addr):
        return []
    s = str(addr).strip()
    variants = [s]
    s2 = s.replace("мкр.", "микрорайон").replace("ул.", "улица") \
          .replace("пр.", "проспект").replace("пр-т", "проспект")
    variants.append(s2)
    # убрать микрорайон
    s3 = re.sub(r"микрорайон\s+\S+,?\s*", "", s2, flags=re.IGNORECASE).strip(" ,")
    if s3 and s3 != s2:
        variants.append(s3)
    return list(dict.fromkeys(v for v in variants if v.strip()))

to_fix = df[df["lat"].isna()].index.tolist()
print(f"Осталось геокодировать: {len(to_fix)}")

found = 0
still_missing = []

for i in to_fix:
    addr = df.loc[i, "address"]
    name = df.loc[i, "name"]
    resolved = False

    for variant in clean_variants(addr):
        # 1. 2GIS
        lat, lon = twogis_geocode(variant)
        if lat:
            df.loc[i, "lat"] = lat
            df.loc[i, "lon"] = lon
            df.loc[i, "method"] = "2gis"
            print(f"✓ 2GIS  {name[:40]} | {variant}")
            resolved = True
            found += 1
            break
        time.sleep(0.3)

    if not resolved:
        still_missing.append({"name": name, "address": addr})
        print(f"✗       {name[:40]} | {addr}")

print(f"\nНайдено: {found}/{len(to_fix)}")
print(f"Осталось NaN: {df['lat'].isna().sum()}")
print(f"Дупликатов: {df.duplicated(subset=['lat','lon']).sum()}")

df.to_csv("kindergartens_almaty_private_osm_matched_final.csv", index=False)

# Сохранить список которые не удалось найти вообще
if still_missing:
    pd.DataFrame(still_missing).to_csv("final_not_found.csv", index=False)
    print(f"Список не найденных → final_not_found.csv")

Осталось геокодировать: 129
✗       Детский сад "АЗИМКА" | ул. Дегдара, 36/1
✗       Детский центр "Kinder land" | ул. Ш. Айтматова, 71
✗       Детский сад "Top Kids 2" | ул. Кенжетаев, 119
✗       Детский сад "Top Kids" | ул. Кенжетаев, 121
✗       Детский сад "Тамирис" | ул. Кенесары-Хан, 116
✗       Детский сад "Талшын" | ул. Сейитбекова, 43
✗       Детский сад «Бала- Дария» филиал | ул. Аширбек Сыгай, 55
✗       Детский сад "Асылым" | ул. Ашимова, 259
✗       Детский сад "АЯНАТ" | ул. Аскарова, 28
✗       Детский сад "Дария Айша" | ул. Қыдырбеков, 60/1
✗       Детский сад "ALATAU" | ул. Афцинао, 11
✗       Детский сад "MARY POPPINS" | ул. Кали-Надырова, 98/1
✗       Детский сад "ЛИМПОПО" | ул. Аширбек Сыгай, 71
✗       Детский сад "БАТЫР-ШИФА" | ул. Кали Надырова, 4
✗       Детский сад "Балапан" | ул. Жалкамыс, 1
✗       Детский сад "Нұрбөпе" | ул. Герольда Бельгера, 57/1
✗       Детский сад "Ерсинтай" | ул. Аспандиярова, 83
✗       Детский сад "ЖАСДИМЕЙР" | ул. Кыдырова, 13
✗       Детский сад "Кенгуренок-А" | ул. Сейтметова, 87
✗       Детский сад "Бала шак" | ул. Акбата, 68
✗       Детский сад "Сарқыт-А" | ул. Болатхан Тайжан, 29
✗       Детский сад "Ақ-Аянұр" | ул. Ибрая Жакаева, 85
✗       Детский сад "Баттыл" | ул. Қарлығаш, 7
✗       Детский сад «АЙГОЛЕК-1» | ул. Сейтметов, 102
✗       Детский сад "Ади" | ул. Даулеткерей, 25
✗       Детский сад "Bаmbino" | ул. Кыдырбекова, 60/1
✗       Детский сад " Радуга" | ул. Таргап, 11
✗       Детский сад "Жануя" | ул. Бекешева, 4
✗       Детский сад "Адеми" | ул. Луганского, 151
✗       Детский сад "SymLynn" | ул. Затаевича, 77
✗       Детский сад "Koktobe" | ул. Найманбаева, 95
✗       Детский сад "Балбөбек" | Территория СТ Жетысу, 39
✗       Детский сад "Батыр Ел" | ул. Верненская, 73
✗       Детский сад "Ботақан" | ул. Есенберлина, 155
✗       Детский сад "My kid" | ул. Аманжола, 54
✗       Детский сад "Alishka" | ул. Янушкевича, 49
✗       Детский сад "Панда" | ул. Орманова, 32 А
✗       Детский сад "Rani" | ул. Жиренше, 75а
✗       Детский сад "ErnarRai" | ул. Шакшак Жанибека, 45/1
✗       Детский сад "Нұр-Айбек" | Улица Каркаралы, 27а
✗       Детский сад "Талант" | ул. Митина, 23А
✗       Ясли-сад "Еркем-Ай" | ул. Жамакаева, 93
✗       Детский сад "Еркетай" | ул. Каркаралы, 23а
✗       Детский сад «Эльсана» | ул. Зверева, 28
✗       Детский сад "StArt" | ул. Кармысова, 90
✗       Детский сад "KULPASH" | ул. Жуковского, 7
✗       Детский сад "АлдиАмир | ул. Сырмак, 44А
✗       Детский сад "Аликош" | ул. Домбыра, 28
✗       Детский сад «Aqbesik»" | ул. Клубная, 24
✗       Детский сад "Бэби Сад" | ул. Каирбекова, 37
✗       Детский сад "Березка" | ул. Рубинштейна, 3а
✗       Детский сад "Alina" | ул. Каирбекова, 68
✗       Детский сад "Умняшка" | ул. Ибрагимова, 105
✗       Детский сад "Алина" | ул. Сахариева, 11
✗       Детский сад "Дана Бала" | ул. Текемет, 40а
✗       Детский сад "BabyBoom 3" | ул. Поповича, 45
✗       Детский сад "GRAMMY" | ул. Жамакаева, 46
✗       Детский сад "TILVALDY" | ул. Нурмагамбетова, 202
✗       Детский сад "Ai-bota" | ул. Аныракай, 6
✗       Детский сад «Bambi» | мкр. Айнабулак-4, 167а
✗       Детский сад "Львёнок" | ул. Жансугуров, 250
✗       Детский сад "АДИНА-Д" | ул. Табигат, 1
✗       Детский сад "Мадина -27" | ул. Молодежная, 69А
✗       Детский сад "Дария 23" | ул. Пестковского, 54
✗       Детский сад "Тедди" | ул. Венецианова, 21А
✗       Детский сад "Умит Ай" | мкр. Кокжиек, 7а
✗       Детский сад "Аиша" | ул. Саялы, 14
✗       Детский сад "Ай-Лау" | ул. Фаворского, 12
✗       Детский сад "БӨПЕШІМ" | ул. Парковая, 2
✗       Детский сад «Даниал» | ул. Куратова, 58
✗       Детский сад "Қарлығаш1" | ул. Грушовая, 12а
✗       Детский сад «Мечта» | ул. Минина, 24
✗       Детский сад "KIS" | пр. Аль-Фараби, 118/15
✗       Детский сад "Балашым" | ул. Попова, 27
✗       Детский сад "ЛИДЕР" | мкр. Орбита 4, 25б
✗       Детский сад "Бэбисити 3" | ул. Кекилбайулы, 45
✗       Детский сад "Tarlan kids" | ул. Кенесары хан, 67
✗       Детский сад "УМКА" | ул. Си Синхая, 1
✗       Детский сад "Болашак" | пр. Сейфуллина, 544
✗       Детский сад "Балажан" | ул. Жандосова, 14
✗       Детский сад "Р-Мурагер 2" | ул. Санаторная, 12
✗       Детский сад «ЭЛКО» | мкр. Орбита 3, 8а
✗       Детский сад "Зайка" | ул. Маркова, 9
✗       Детский сад "Симба Kids" | ул. Кекилбайулы, 32А
✗       Детский сад "Мидас" | ул. Журавлева, 22
✗       Детский сад "Кулагер" | мкр. Казахфильм, 45
✗       Детский сад "Алгабас-3 | ул. Озтюрка, 5А
✗       Филиал "Образовательного комплекса школы | мкр. Мирас, 59
✗       Детский сад "Ахмадиева" | ул. Подгорная, 25/2
✗       Детский сад "Альтар" | ул. Булбул, 8/2
✗       Детский сад "Айару" | ул. Попова, 22
✗       Ясли-сад "Зердеш-3" | ул. Болтириковой, 50
✗       Детский сад "МЕГА КИДС" (филиал) | 11-я улица, 8
✗       Детский сад "Mykid2" | 6-я улица, 25
✗       Детский сад "Аль-Фараби" | ул. Рафика Нуртазина, 79
✗       Детский сад «Sparks Preschool» | мкр. Мирас, 160
✗       Детский сад "Эрудиты" | ул. 20 линия, 62
✗       Детский сад "Умка" | ул. Киргизская, 2
✗       Детский сад "Уайз Кидс" | ул. Кольсай, 31
✗       Детский сад "QazBaby" | ул. Бұлбұл, 17
✗       Детский сад "Бэби_клуб" | мкр. Мамыр-7, 8/4
✗       Детский садик "Чебурашка" | мкр. Алтын бесик, 177
✗       Детский сад "Асемгул-1" | мкр. Алтын Бесик, 53
✗       Детский сад "Қарлығаш" | мкр. Алтын Бесик, 168
✗       Детский сад «Еркежан» | мкр. Алтын бесік, 223
✗       Детский сад "Қонжықтар" | ул. Римова, 11
✗       Детский сад "Айсәт" | ул. Әнет баба, 37
✗       Детский сад "Жан -Дария" | ул. Акшагыл, 23
✗       Детский сад "Ақсұнқар" | ул. Игілік, 11
✗       Детский сад "Ертарғын" | ул. Арқалық, 19/6
✗       Детский сад "Хан-Тәңірі-7" | ул. Василия Бенберина, 38/1
✗       Детский сад "Бексұлтан 7" | ул. Кокжайлау, 7
✗       Детский сад "Нұр-Сәт1" | ул. Абылай хан, 10
✗       Детский-сад "Аяла" | ул. Аркалык, 52А
✗       Детский сад "Молдир-2" | ул. Жанкожа батыр, 73
✗       Детский сад "Тұмар-А" | Квартал Жаңа құрылыс, 211
✗       Детский сад "Айша" | ул. Ақтілек, 8
✗       Детский сад «Азя» | ул. Байтенева, 129
✗       Детский сад "Еркемай" | ул. Доспанова, 22
✗       Детский сад "Мәржол" | ул. Арқалық, 68
✗       Детский сад «Акбопе» | Мамытов көш., 94/13
✗       ТОО детский сад "Құралай Кидс" | ул. Доспанова, 20
✗       ТОО детский сад "АдиРай" | ул. Алпамыс, 125/1
✗       ТОО "Детский сад Бекося" | ул. Курти, 18
✗       ТОО детский сад "Хан-9" | ул. Аркалык, 25/1
✗       Детский сад "BoBo"" | ул. Акшагыл, 28/3
✗       детский сад "AIZARA" | ул. Байдібек би, 134
✗       ТОО детский сад "NAZ" | ул. Тойшыбек Батыр, 68
✗       ТОО детский сад "Сержан- К" | ул. Аркалык, 6/1

Найдено: 0/129
Осталось NaN: 129
Дупликатов: 163
Список не найденных → final_not_found.csv

In [36]:
import pandas as pd
import requests
import time
import re

df = pd.read_csv("kindergartens_almaty_private_osm_matched_final.csv")

def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15

def twogis_geocode(addr):
    try:
        r = requests.get(
            "https://catalog.api.2gis.com/3.0/items/geocode",
            params={
                "q": f"{addr}, Алматы",
                "fields": "items.point",
                "key": "rubimap",
                "locale": "ru_KZ",
            },
            timeout=10
        )
        for item in r.json().get("result", {}).get("items", []):
            pt = item.get("point", {})
            lat, lon = pt.get("lat"), pt.get("lon")
            if lat and lon and in_bbox(lat, lon):
                return lat, lon
    except Exception as e:
        print(f"  2GIS error: {e}")
    return None, None

to_fix = df[df["lat"].isna()].index.tolist()
print(f"Геокодируем: {len(to_fix)} садов")

found = 0
for i in to_fix:
    addr = str(df.loc[i, "address"])
    name = df.loc[i, "name"]
    
    # Пробуем оригинал и нормализованный адрес
    variants = [addr]
    addr2 = addr.replace("мкр.", "микрорайон").replace("ул.", "улица").replace("пр.", "проспект")
    if addr2 != addr:
        variants.append(addr2)
    
    resolved = False
    for v in variants:
        lat, lon = twogis_geocode(v)
        if lat:
            df.loc[i, "lat"] = lat
            df.loc[i, "lon"] = lon
            df.loc[i, "method"] = "2gis"
            print(f"✓ {name[:45]} | {v}")
            found += 1
            resolved = True
            break
        time.sleep(0.3)
    
    if not resolved:
        print(f"✗ {name[:45]} | {addr}")

print(f"\nНайдено: {found}/{len(to_fix)}")
print(f"Осталось NaN: {df['lat'].isna().sum()}")
print(f"Дупликатов: {df.duplicated(subset=['lat','lon']).sum()}")

df.to_csv("kindergartens_almaty_private_osm_matched_final11.csv", index=False)

Геокодируем: 129 садов
✗ Детский сад "АЗИМКА" | ул. Дегдара, 36/1
✗ Детский центр "Kinder land" | ул. Ш. Айтматова, 71
✗ Детский сад "Top Kids 2" | ул. Кенжетаев, 119
✗ Детский сад "Top Kids" | ул. Кенжетаев, 121
✗ Детский сад "Тамирис" | ул. Кенесары-Хан, 116
✗ Детский сад "Талшын" | ул. Сейитбекова, 43
✗ Детский сад «Бала- Дария» филиал | ул. Аширбек Сыгай, 55
✗ Детский сад "Асылым" | ул. Ашимова, 259
✗ Детский сад "АЯНАТ" | ул. Аскарова, 28
✗ Детский сад "Дария Айша" | ул. Қыдырбеков, 60/1
✗ Детский сад "ALATAU" | ул. Афцинао, 11
✗ Детский сад "MARY POPPINS" | ул. Кали-Надырова, 98/1
✗ Детский сад "ЛИМПОПО" | ул. Аширбек Сыгай, 71
✗ Детский сад "БАТЫР-ШИФА" | ул. Кали Надырова, 4
✗ Детский сад "Балапан" | ул. Жалкамыс, 1
✗ Детский сад "Нұрбөпе" | ул. Герольда Бельгера, 57/1
✗ Детский сад "Ерсинтай" | ул. Аспандиярова, 83
✗ Детский сад "ЖАСДИМЕЙР" | ул. Кыдырова, 13
✗ Детский сад "Кенгуренок-А" | ул. Сейтметова, 87
✗ Детский сад "Бала шак" | ул. Акбата, 68
✗ Детский сад "Сарқыт-А" | ул. Болатхан Тайжан, 29
✗ Детский сад "Ақ-Аянұр" | ул. Ибрая Жакаева, 85
✗ Детский сад "Баттыл" | ул. Қарлығаш, 7
✗ Детский сад «АЙГОЛЕК-1» | ул. Сейтметов, 102
✗ Детский сад "Ади" | ул. Даулеткерей, 25
✗ Детский сад "Bаmbino" | ул. Кыдырбекова, 60/1
✗ Детский сад " Радуга" | ул. Таргап, 11
✗ Детский сад "Жануя" | ул. Бекешева, 4
✗ Детский сад "Адеми" | ул. Луганского, 151
✗ Детский сад "SymLynn" | ул. Затаевича, 77
✗ Детский сад "Koktobe" | ул. Найманбаева, 95
✗ Детский сад "Балбөбек" | Территория СТ Жетысу, 39
✗ Детский сад "Батыр Ел" | ул. Верненская, 73
✗ Детский сад "Ботақан" | ул. Есенберлина, 155
✗ Детский сад "My kid" | ул. Аманжола, 54
✗ Детский сад "Alishka" | ул. Янушкевича, 49
✗ Детский сад "Панда" | ул. Орманова, 32 А
✗ Детский сад "Rani" | ул. Жиренше, 75а
✗ Детский сад "ErnarRai" | ул. Шакшак Жанибека, 45/1
✗ Детский сад "Нұр-Айбек" | Улица Каркаралы, 27а
✗ Детский сад "Талант" | ул. Митина, 23А
✗ Ясли-сад "Еркем-Ай" | ул. Жамакаева, 93
✗ Детский сад "Еркетай" | ул. Каркаралы, 23а
✗ Детский сад «Эльсана» | ул. Зверева, 28
✗ Детский сад "StArt" | ул. Кармысова, 90
✗ Детский сад "KULPASH" | ул. Жуковского, 7
✗ Детский сад "АлдиАмир | ул. Сырмак, 44А
✗ Детский сад "Аликош" | ул. Домбыра, 28
✗ Детский сад «Aqbesik»" | ул. Клубная, 24
✗ Детский сад "Бэби Сад" | ул. Каирбекова, 37
✗ Детский сад "Березка" | ул. Рубинштейна, 3а
✗ Детский сад "Alina" | ул. Каирбекова, 68
✗ Детский сад "Умняшка" | ул. Ибрагимова, 105
✗ Детский сад "Алина" | ул. Сахариева, 11
✗ Детский сад "Дана Бала" | ул. Текемет, 40а
✗ Детский сад "BabyBoom 3" | ул. Поповича, 45
✗ Детский сад "GRAMMY" | ул. Жамакаева, 46
✗ Детский сад "TILVALDY" | ул. Нурмагамбетова, 202
✗ Детский сад "Ai-bota" | ул. Аныракай, 6
✗ Детский сад «Bambi» | мкр. Айнабулак-4, 167а
✗ Детский сад "Львёнок" | ул. Жансугуров, 250
✗ Детский сад "АДИНА-Д" | ул. Табигат, 1
✗ Детский сад "Мадина -27" | ул. Молодежная, 69А
✗ Детский сад "Дария 23" | ул. Пестковского, 54
✗ Детский сад "Тедди" | ул. Венецианова, 21А
✗ Детский сад "Умит Ай" | мкр. Кокжиек, 7а
✗ Детский сад "Аиша" | ул. Саялы, 14
✗ Детский сад "Ай-Лау" | ул. Фаворского, 12
✗ Детский сад "БӨПЕШІМ" | ул. Парковая, 2
✗ Детский сад «Даниал» | ул. Куратова, 58
✗ Детский сад "Қарлығаш1" | ул. Грушовая, 12а
✗ Детский сад «Мечта» | ул. Минина, 24
✗ Детский сад "KIS" | пр. Аль-Фараби, 118/15
✗ Детский сад "Балашым" | ул. Попова, 27
✗ Детский сад "ЛИДЕР" | мкр. Орбита 4, 25б
✗ Детский сад "Бэбисити 3" | ул. Кекилбайулы, 45
✗ Детский сад "Tarlan kids" | ул. Кенесары хан, 67
✗ Детский сад "УМКА" | ул. Си Синхая, 1
✗ Детский сад "Болашак" | пр. Сейфуллина, 544
✗ Детский сад "Балажан" | ул. Жандосова, 14
✗ Детский сад "Р-Мурагер 2" | ул. Санаторная, 12
✗ Детский сад «ЭЛКО» | мкр. Орбита 3, 8а
✗ Детский сад "Зайка" | ул. Маркова, 9
✗ Детский сад "Симба Kids" | ул. Кекилбайулы, 32А
✗ Детский сад "Мидас" | ул. Журавлева, 22
✗ Детский сад "Кулагер" | мкр. Казахфильм, 45
✗ Детский сад "Алгабас-3 | ул. Озтюрка, 5А
✗ Филиал "Образовательного комплекса школы "Fir | мкр. Мирас, 59
✗ Детский сад "Ахмадиева" | ул. Подгорная, 25/2
✗ Детский сад "Альтар" | ул. Булбул, 8/2
✗ Детский сад "Айару" | ул. Попова, 22
✗ Ясли-сад "Зердеш-3" | ул. Болтириковой, 50
✗ Детский сад "МЕГА КИДС" (филиал) | 11-я улица, 8
✗ Детский сад "Mykid2" | 6-я улица, 25
✗ Детский сад "Аль-Фараби" | ул. Рафика Нуртазина, 79
✗ Детский сад «Sparks Preschool» | мкр. Мирас, 160
✗ Детский сад "Эрудиты" | ул. 20 линия, 62
✗ Детский сад "Умка" | ул. Киргизская, 2
✗ Детский сад "Уайз Кидс" | ул. Кольсай, 31
✗ Детский сад "QazBaby" | ул. Бұлбұл, 17
✗ Детский сад "Бэби_клуб" | мкр. Мамыр-7, 8/4
✗ Детский садик "Чебурашка" | мкр. Алтын бесик, 177
✗ Детский сад "Асемгул-1" | мкр. Алтын Бесик, 53
✗ Детский сад "Қарлығаш" | мкр. Алтын Бесик, 168
✗ Детский сад «Еркежан» | мкр. Алтын бесік, 223
✗ Детский сад "Қонжықтар" | ул. Римова, 11
✗ Детский сад "Айсәт" | ул. Әнет баба, 37
✗ Детский сад "Жан -Дария" | ул. Акшагыл, 23
✗ Детский сад "Ақсұнқар" | ул. Игілік, 11
✗ Детский сад "Ертарғын" | ул. Арқалық, 19/6
✗ Детский сад "Хан-Тәңірі-7" | ул. Василия Бенберина, 38/1
✗ Детский сад "Бексұлтан 7" | ул. Кокжайлау, 7
✗ Детский сад "Нұр-Сәт1" | ул. Абылай хан, 10
✗ Детский-сад "Аяла" | ул. Аркалык, 52А
✗ Детский сад "Молдир-2" | ул. Жанкожа батыр, 73
✗ Детский сад "Тұмар-А" | Квартал Жаңа құрылыс, 211
✗ Детский сад "Айша" | ул. Ақтілек, 8
✗ Детский сад «Азя» | ул. Байтенева, 129
✗ Детский сад "Еркемай" | ул. Доспанова, 22
✗ Детский сад "Мәржол" | ул. Арқалық, 68
✗ Детский сад «Акбопе» | Мамытов көш., 94/13
✗ ТОО детский сад "Құралай Кидс" | ул. Доспанова, 20
✗ ТОО детский сад "АдиРай" | ул. Алпамыс, 125/1
✗ ТОО "Детский сад Бекося" | ул. Курти, 18
✗ ТОО детский сад "Хан-9" | ул. Аркалык, 25/1
✗ Детский сад "BoBo"" | ул. Акшагыл, 28/3
✗ детский сад "AIZARA" | ул. Байдібек би, 134
✗ ТОО детский сад "NAZ" | ул. Тойшыбек Батыр, 68
✗ ТОО детский сад "Сержан- К" | ул. Аркалык, 6/1

Найдено: 0/129
Осталось NaN: 129
Дупликатов: 163

In [17]:
not_found.to_csv("not_found.csv", index=False)

In [3]:
# osm_match_schools_batch_fixed.py

import os
import re
import time
import pandas as pd
import requests
from difflib import SequenceMatcher
from tqdm import tqdm

# ===================== НАСТРОЙКИ =====================
IN_CSV  = "kindergartens_almaty_osm_matched.csv"
OUT_CSV = "kindergartens_almaty_osm_matched_final.csv"
OSM_DUMP_CSV = "kindergartens_almaty_osm_matched_dump.csv"
NOT_FOUND_CSV = "kindergartens_almaty_osm_not_found.csv"

# bbox Алматы
BBOX = (43.10, 76.70, 43.45, 77.15)

OVERPASS_URLS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass.openstreetmap.ru/api/interpreter",
]

HEADERS = {"User-Agent": "almaty-osm-school-matcher/2.0"}

ALMATY_LAT = 43.2389
ALMATY_LON = 76.8897

# ===================== OSM =====================
def download_osm_schools(bbox):
    south, west, north, east = bbox

    q = f"""
    [out:json][timeout:180];
    (
        node["amenity"="kindergarten"]({south},{west},{north},{east});
        way["amenity"="kindergarten"]({south},{west},{north},{east});
        relation["amenity"="kindergarten"]({south},{west},{north},{east});

        // иногда размечены как building
        node["building"="kindergarten"]({south},{west},{north},{east});
        way["building"="kindergarten"]({south},{west},{north},{east});
        relation["building"="kindergarten"]({south},{west},{north},{east});
    );
    out center tags;
    """

    for base in OVERPASS_URLS:
        for attempt in range(5):
            try:
                r = requests.post(base, data=q.encode("utf-8"), headers=HEADERS, timeout=240)
                if r.status_code in (429, 502, 503, 504):
                    time.sleep(2 * (attempt + 1))
                    continue

                r.raise_for_status()
                js = r.json()

                rows = []
                for e in js.get("elements", []):
                    tags = e.get("tags", {}) or {}

                    if e["type"] == "node":
                        lat, lon = e.get("lat"), e.get("lon")
                    else:
                        c = e.get("center") or {}
                        lat, lon = c.get("lat"), c.get("lon")

                    if lat is None or lon is None:
                        continue

                    rows.append({
                        "osm_type": e["type"],
                        "osm_id": e["id"],
                        "name": tags.get("name"),
                        "name_ru": tags.get("name:ru"),
                        "lat": lat,
                        "lon": lon,
                    })

                return pd.DataFrame(rows)

            except Exception:
                time.sleep(2)

    raise RuntimeError("Overpass failed")

# ===================== MATCHING =====================
def norm(s):
    if s is None:
        return ""
    s = str(s).lower()
    s = s.replace("ё", "е").replace("№", " no ")
    s = re.sub(r"[^0-9a-zа-я\s]", " ", s)
    return re.sub(r"\s+", " ", s).strip()

def extract_number(s):
    s = norm(s)
    m = re.search(r"\bno\s*(\d+)", s)
    if m:
        return m.group(1)
    m = re.search(r"школ[а-я]*\s*(\d+)", s)
    if m:
        return m.group(1)
    return None

def similarity(a, b):
    return SequenceMatcher(None, a, b).ratio()

def best_match(name, osm):
    target = norm(name)
    num = extract_number(name)

    cand = osm
    if num:
        tmp = osm[osm["name_norm"].str.contains(num, na=False)]
        if len(tmp) > 0:
            cand = tmp

    exact = cand[cand["name_norm"] == target]
    if len(exact) > 0:
        r = exact.iloc[0]
        return r, "exact", 1.0

    best = None
    best_score = 0

    for _, r in cand.iterrows():
        sc = similarity(target, r["name_norm"])
        if sc > best_score:
            best_score = sc
            best = r

    if best_score < (0.62 if num else 0.72):
        return None, None, None

    return best, "fuzzy", best_score

# ===================== GEOCODERS =====================
def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15

photon_cache = {}
def photon_geocode(q):
    if q in photon_cache:
        return photon_cache[q]

    url = "https://photon.komoot.io/api"
    try:
        r = requests.get(url, params={"q": q, "limit": 1}, timeout=10)
        js = r.json()
        feats = js.get("features", [])
        if feats:
            lon, lat = feats[0]["geometry"]["coordinates"]
            if in_bbox(lat, lon):
                photon_cache[q] = (lat, lon)
                return lat, lon
    except:
        pass

    photon_cache[q] = (None, None)
    return None, None

# ===================== MAIN =====================
def main():
    df = pd.read_csv(IN_CSV)

    # OSM
    if os.path.exists(OSM_DUMP_CSV):
        osm = pd.read_csv(OSM_DUMP_CSV)
    else:
        osm = download_osm_schools(BBOX)
        osm.to_csv(OSM_DUMP_CSV, index=False)

    osm["name_best"] = osm["name_ru"].fillna(osm["name"]).fillna("")
    osm["name_norm"] = osm["name_best"].apply(norm)

    # OUTPUT
    out = df.copy()
    out["lat"] = None
    out["lon"] = None
    out["method"] = None
    out["score"] = None

    # 1. OSM matching
    for i, row in tqdm(out.iterrows(), total=len(out)):
        res, method, score = best_match(row["name"], osm)
        if res is not None:
            out.at[i, "lat"] = res["lat"]
            out.at[i, "lon"] = res["lon"]
            out.at[i, "method"] = method
            out.at[i, "score"] = score

    # 2. Photon fallback
    for i in tqdm(out[out["lat"].isna()].index):
        addr = str(out.at[i, "address"])
        lat, lon = photon_geocode(addr + ", Алматы")

        if lat:
            out.at[i, "lat"] = lat
            out.at[i, "lon"] = lon
            out.at[i, "method"] = "photon"

        time.sleep(0.2)

    # 3. Nominatim fallback
    from geopy.exc import GeocoderTimedOut, GeocoderUnavailable

    geo = Nominatim(user_agent="almaty-final", timeout=10)

    geocode = RateLimiter(
        geo.geocode,
        min_delay_seconds=1.2,
        max_retries=3,
        error_wait_seconds=5
    )
    
    for i in tqdm(out[out["lat"].isna()].index):
        addr = str(out.at[i, "address"])
        try:
            loc = geocode(addr + ", Алматы, Казахстан")
            if loc and in_bbox(loc.latitude, loc.longitude):
                out.at[i, "lat"] = loc.latitude
                out.at[i, "lon"] = loc.longitude
                out.at[i, "method"] = "nominatim"
        except (GeocoderTimedOut, GeocoderUnavailable):
            continue

    # confidence
    def conf(row):
        if row["method"] == "exact":
            return "high"
        if row["method"] == "fuzzy" and row["score"] > 0.8:
            return "high"
        if row["method"] in ["photon", "nominatim"]:
            return "medium"
        return "low"

    out["confidence"] = out.apply(conf, axis=1)

    out.to_csv(OUT_CSV, index=False)
    out[out["lat"].isna()].to_csv(NOT_FOUND_CSV, index=False)

    print("DONE")
    print("Found:", out["lat"].notna().sum())
    print("Not found:", out["lat"].isna().sum())

if __name__ == "__main__":
    main()

100%|██████████| 198/198 [00:01<00:00, 152.30it/s]
100%|██████████| 37/37 [00:26<00:00,  1.42it/s]
100%|██████████| 37/37 [00:43<00:00,  1.19s/it]

DONE
Found: 176
Not found: 22

In [3]:
import pandas as pd
import requests
import time
import re

df = pd.read_csv("kindergartens_almaty_private_osm_matched_final.csv")

YANDEX_KEY = "4e0aaf8d-4ab5-4be2-be63-7327bbe09df2"

def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15

def clean(addr):
    """Убираем сокращения — геокодер лучше понимает полные слова или вообще без них"""
    addr = str(addr).strip()
    addr = re.sub(r'\bул\.\s*', '', addr)
    addr = re.sub(r'\bпр\.\s*', '', addr)
    addr = re.sub(r'\bпр-т\s*', '', addr)
    addr = re.sub(r'\bмкр\.\s*', 'микрорайон ', addr)
    addr = re.sub(r'\bпер\.\s*', '', addr)
    addr = re.sub(r'\s+', ' ', addr).strip(' ,')
    return addr

def yandex_geocode(addr):
    c = clean(addr)
    variants = [
        f"Алматы, {addr}",           # оригинал: Алматы, ул. Аскарова, 28
        f"Алматы, {c}",              # без сокращений: Алматы, Аскарова, 28
        f"Алматы {c}",               # без запятой: Алматы Аскарова 28
        f"Казахстан, Алматы, {c}",   # с полным путём
    ]
    
    for q in variants:
        try:
            r = requests.get(
                "https://geocode-maps.yandex.ru/1.x/",
                params={
                    "apikey": YANDEX_KEY,
                    "geocode": q,
                    "format": "json",
                    "ll": "76.89,43.24",
                    "spn": "0.35,0.25",
                    "rspn": 1,
                    "results": 1,
                    "lang": "ru_RU"
                },
                timeout=10
            )
            members = r.json()["response"]["GeoObjectCollection"]["featureMember"]
            if members:
                pos = members[0]["GeoObject"]["Point"]["pos"].split()
                lon, lat = float(pos[0]), float(pos[1])
                if in_bbox(lat, lon):
                    return lat, lon, q
        except Exception as e:
            print(f"  ошибка: {e}")
        time.sleep(0.2)
    
    return None, None, None

to_fix = df[df["lat"].isna()].index.tolist()
print(f"Геокодируем: {len(to_fix)} адресов\n")

found = 0
not_found = []

for i in to_fix:
    addr = str(df.loc[i, "address"])
    name = df.loc[i, "name"]
    
    lat, lon, matched_q = yandex_geocode(addr)
    
    if lat:
        df.loc[i, "lat"] = lat
        df.loc[i, "lon"] = lon
        df.loc[i, "method"] = "yandex"
        print(f"✓ {name[:45]}")
        print(f"  {addr} → {lat:.5f}, {lon:.5f}")
        found += 1
    else:
        not_found.append({"name": name, "address": addr})
        print(f"✗ {name[:45]} | {addr}")
    
    time.sleep(0.2)

print(f"\n{'='*50}")
print(f"Найдено:       {found}/{len(to_fix)}")
print(f"Осталось NaN:  {df['lat'].isna().sum()}")
print(f"Дупликатов:    {df.duplicated(subset=['lat','lon']).sum()}")

df.to_csv("kindergartens_almaty_private_osm_matched_final.csv", index=False)

if not_found:
    pd.DataFrame(not_found).to_csv("still_not_found.csv", index=False)
    print(f"\nНе найдено → still_not_found.csv ({len(not_found)} штук)")

Геокодируем: 9 адресов

✗ Детский сад "АЗИМКА" | ул. Дегдара, 36/1
✗ Детский сад «Бала- Дария» филиал | ул. Аширбек Сыгай, 55
✗ Детский сад "АЯНАТ" | ул. Аскарова, 28
✗ Детский сад "Мадина -27" | ул. Молодежная, 69А
✗ Детский сад «ЭЛКО» | мкр. Орбита 3, 8а
✗ Детский сад "Ахмадиева" | ул. Подгорная, 25/2
✗ Детский сад "Хан-Тәңірі-7" | ул. Василия Бенберина, 38/1
✗ Детский сад "Тұмар-А" | Квартал Жаңа құрылыс, 211
✗ Детский сад "Мәржол" | ул. Арқалық, 68

==================================================
Найдено:       0/9
Осталось NaN:  9
Дупликатов:    44

Не найдено → still_not_found.csv (9 штук)

In [4]:
dups = df[df.duplicated(subset=["lat","lon"], keep=False)].sort_values(["lat","lon"])
print(dups[["name","address","lat","lon","method"]].to_string())

                                                                  name                      address        lat        lon           method
403                                                 Детский сад "Нэмо"          мкр. Атамекен, 163А  43.207334  76.849053  nominatim_dedup
405                               Детский сад "Білім балалар орталығы"          мкр. Атамекен, 163А  43.207334  76.849053              NaN
425                                   Детский-ясли сад "Береке - 2020"          мкр. Атамекен, 33/1  43.207593  76.844508  nominatim_dedup
476                                        Детский сад "Тимас компани"          мкр. Атамекен, 33/1  43.207593  76.844508              NaN
387                                       Детский сад "Altyn Gasyr_KZ"             мкр. Мамыр-7, 21  43.212152  76.840487              NaN
440                                      Детский сад "Antaress kids-2"              мкр. Алмас, 106  43.212152  76.840487  nominatim_dedup
451                                               Детский сад "Айсана"              мкр. Алмас, 134  43.212152  76.840487  nominatim_dedup
473                                             Детский сад "Ару kids"              мкр. Алмас, 201  43.212152  76.840487  nominatim_dedup
493                                            Детский сад "Садок ltd"              мкр. Алмас, 172  43.212152  76.840487  nominatim_dedup
431                                                Мини-центр "i.Bala"             мкр. Мамыр 4, 18  43.214040  76.854358              NaN
467                                             Детский сад "i.Bala 2"             мкр. Мамыр 4, 18  43.214040  76.854358  nominatim_dedup
337                                          Детский сад "ERKE A kids"          ул. Тажибаевой, 180  43.214124  76.891300        nominatim
384                                    Детский сад "Joy Art Education"          ул. Тажибаевой, 180  43.214124  76.891300        nominatim
404                                           Детский сад "Таргап А&K"            мкр. Мамыр 4, 128  43.214311  76.844594              NaN
486                                               Детский сад "ШамШер"            мкр. Мамыр 4, 128  43.214311  76.844594  nominatim_dedup
394                                          Детский сад "Lion Garden"              мкр. Алмас, 57а  43.214799  76.869270              NaN
443                                                 Детский сад "УМКА"            мкр. Мамыр-4, 57А  43.214799  76.869270  nominatim_dedup
397                                             Детский сад "Умка Сад"            мкр. Мамыр-4, 166  43.215713  76.852208  nominatim_dedup
435                                               Детский сад "Эврика"             мкр. Мамыр 4, 4Б  43.215713  76.852208  nominatim_dedup
461                                                Детский сад "Білім"             мкр. Мамыр 4, 4б  43.215713  76.852208  nominatim_dedup
416                                       Мини-центр "Новое поколение"            мкр. Мамыр 7, 8/1  43.215754  76.837410              NaN
420                                     Мини-центр "ДиДи2016" (филиал)            мкр. Мамыр-7, 8/1  43.215754  76.837410  nominatim_dedup
148                                           Детский сад "Дария Айша"         ул. Қыдырбеков, 60/1  43.215998  76.804259           yandex
188                                              Детский сад "Bаmbino"        ул. Кыдырбекова, 60/1  43.215998  76.804259           yandex
412                                        Детский сад "Antaress Kids"            мкр. Мамыр-4, 156  43.216051  76.849806              NaN
494                                               Мини-центр "АйДиНур"            мкр. Мамыр 4, 156  43.216051  76.849806  nominatim_dedup
100                                           Детский сад "CӘТ-БЕРЕКЕ"         ул. Жунисова, 134/80  43.218856  76.790825  nominatim_dedup
106                                          Детский сад "Aizere 2020"           ул. Жунисова, 2/87  43.218856  76.790825        nominatim
127                                            Мини-центр "Чудо-детки"              ул. Таргап, 111  43.219009  76.795306        nominatim
162                                       Детский сад "Smart Children"              ул. Таргап, 111  43.219009  76.795306        nominatim
78   Детский сад "Алматинская математико-лингвистическая школа "Самай"       ул. Аширбек Сыгай, 124  43.220923  76.792445        nominatim
82                                        Детский сад "Munarat Almaty"        ул. Аширбек Сыгай, 96  43.220923  76.792445  nominatim_dedup
227                                        Детский сад "Villa Bambini"            ул. Таттимбета, 3  43.223372  76.967799        nominatim
248                                      Детский сад "Чудесная страна"            ул. Таттимбета, 3  43.223372  76.967799        nominatim
134                                           Детский сад "Бала-Дария"          ул. Айбергенова, 92  43.223932  76.796668  nominatim_dedup
137                                               Детский сад "Сұңқар"          ул. Айбергенова, 92  43.223932  76.796668  nominatim_dedup
468                                               Детский Центр "Умка"            мкр. Аксай 3а, 85  43.235693  76.826545  nominatim_dedup
481                                   Детский сад "СӘТТІЛІК & БОЛАШАҚ"             мкр. Мамыр 3, 3А  43.235693  76.826545              NaN
278                                            Детский сад "Parasat-S"       мкр. Айнабулак-3, 172Е  43.236392  76.945728              NaN
474                                                Детский сад "Зере "           мкр. Атамекен, 70Б  43.236392  76.945728  nominatim_dedup
550                                                Детский сад "Арман"        мкр. Мадениет, 288/30  43.236392  76.945728  nominatim_dedup
456                                    Образовательный центр "Арайлым"             мкр. Баянаул, 40  43.239704  76.819395  nominatim_dedup
497                                        Детский сад "Мир детства 1"             мкр. Баянаул, 40  43.239704  76.819395              NaN
580                                         Детский сад "Болашақ и Со"       ул. Казтуган Жырау, 21  43.247665  76.813290        nominatim
699                                 ТОО "Детский сад "Мың бала Алматы"     ул. Казтуган Жырау, 29/1  43.247665  76.813290  nominatim_dedup
567                                          Мини-центр "ЕЛАМАН-КЫЗЫР"             ул. Чуланова, 83  43.253778  76.828289        nominatim
652                                        ТОО детский сад "БАЛ САПАР"             ул. Чуланова, 83  43.253778  76.828289        nominatim
522                                 Детский сад "Алди-Ерке-1" (филиал)           мкр. Туркестан, 77  43.271812  76.852261              NaN
686                                                 ТОО "АҚСАУЛЕ 2023"           мкр. Туркестан, 77  43.271812  76.852261              NaN
556                                           Детский сад "Кун Шуак-М"           ул. Туймебаева, 68  43.275548  76.834737        nominatim
624                                       ТОО "BAL-bala 1 балабақшасы"           ул. Туймебаева, 39  43.275548  76.834737  nominatim_dedup
528                                        Детский сад "Мерей компани"                ул. Текес, 67  43.284888  76.836085  nominatim_dedup
592                                      ТОО детский сад "Төре - Зере"                ул. Текес, 79  43.284888  76.836085        nominatim
39                                          Мини-центр "ЕРКЕМ-АЙ ГОЛД"             ул. Ижевская, 33  43.294301  76.962759        nominatim
49                                             Детский сад "Балдаурен"             ул. Ижевская, 33  43.294301  76.962759  nominatim_dedup
3                                       Мини-центр "Немере и компания"       ул. Каракалпакская, 12  43.296459  76.963379        nominatim
46                                            Детский сад "Bakutalemi"       ул. Каракалпакская, 12  43.296459  76.963379        nominatim
553                                              Детский сад "Зерде-2"             ул. Тайконыр, 41  43.300208  76.890733  nominatim_dedup
581                                                Детский сад "Зерде"             ул. Тайконыр, 41  43.300208  76.890733  nominatim_dedup
651                                          ТОО Ясли сад «Happy kids»     ул. Кожаберген Жырау, 19  43.327219  76.897735        nominatim
667                                       ТОО детский сад "Бақыт нұры"     ул. Кожаберген Жырау, 19  43.327219  76.897735        nominatim
626                                           ТОО "Балабакша "Болашақ"              ул. Асанова, 77  43.337561  77.068094              NaN
693                                         ТОО детский сад "BB DAmir"               ул. Асанова, 7  43.337561  77.068094  nominatim_dedup
36                                            Детский сад "Жансая-Сәт"              ул. Зимняя, 18Б  43.352260  76.986999  nominatim_dedup
44                                              Детский сад "Биржан К"                ул. Зимняя, 2  43.352260  76.986999  nominatim_dedup
24                                              Детский сад "КҮН ШУАҚ"          ул. Дунентаева, 6/4  43.357280  76.995136  nominatim_dedup
47                                               Детский сад "Кокетай"          ул. Дунентаева, 8/1  43.357280  76.995136  nominatim_dedup
30                                                Детский сад "АЗИМКА"            ул. Дегдара, 36/1        NaN        NaN              NaN
144                                   Детский сад «Бала- Дария» филиал        ул. Аширбек Сыгай, 55        NaN        NaN              NaN
147                                                Детский сад "АЯНАТ"             ул. Аскарова, 28        NaN        NaN              NaN
288                                           Детский сад "Мадина -27"          ул. Молодежная, 69А        NaN        NaN              NaN
330                                                 Детский сад «ЭЛКО»            мкр. Орбита 3, 8а        NaN        NaN              NaN
347                                            Детский сад "Ахмадиева"          ул. Подгорная, 25/2        NaN        NaN              NaN
515                                         Детский сад "Хан-Тәңірі-7"  ул. Василия Бенберина, 38/1        NaN        NaN              NaN
558                                              Детский сад "Тұмар-А"    Квартал Жаңа құрылыс, 211        NaN        NaN              NaN
585                                               Детский сад "Мәржол"              ул. Арқалық, 68        NaN        NaN              NaN

In [52]:
import pandas as pd

# Для дупликатов с разными адресами — сбросить координаты у тех у кого method=NaN
# (они получили чужую точку)
dup_mask = df.duplicated(subset=["lat","lon"], keep=False)
dups = df[dup_mask].copy()

reset_count = 0
for (lat, lon), group in dups.groupby(["lat","lon"]):
    unique_addr = group["address"].nunique()
    if unique_addr > 1:
        # оставить только строки с method (они геокодировались сами)
        # сбросить строки у которых method=NaN — они "прилипли" к чужой точке
        nan_method_idx = group[group["method"].isna()].index
        df.loc[nan_method_idx, ["lat","lon"]] = None
        reset_count += len(nan_method_idx)

print(f"Сброшено ложных координат: {reset_count}")
print(f"Осталось NaN: {df['lat'].isna().sum()}")
print(f"Дупликатов: {df.duplicated(subset=['lat','lon']).sum()}")
print()
print("Строки без координат:")
print(df[df["lat"].isna()][["name","address"]].to_string())

df.to_csv("kindergartens_almaty_private_osm_matched_final11.csv", index=False)

Сброшено ложных координат: 0
Осталось NaN: 0
Дупликатов: 29

Строки без координат:
Empty DataFrame
Columns: [name, address]
Index: []

In [54]:
dups = df[df.duplicated(subset=["lat","lon"], keep=False)].sort_values(["lat","lon"])
print(f"Всего дупликатов: {len(dups)}")
print()
print(dups[["name","address","lat","lon","method"]].to_string())

Всего дупликатов: 55

                                                                  name                   address        lat        lon           method
403                                                 Детский сад "Нэмо"       мкр. Атамекен, 163А  43.207334  76.849053  nominatim_dedup
405                               Детский сад "Білім балалар орталығы"       мкр. Атамекен, 163А  43.207334  76.849053              NaN
425                                   Детский-ясли сад "Береке - 2020"       мкр. Атамекен, 33/1  43.207593  76.844508  nominatim_dedup
476                                        Детский сад "Тимас компани"       мкр. Атамекен, 33/1  43.207593  76.844508              NaN
440                                      Детский сад "Antaress kids-2"           мкр. Алмас, 106  43.212152  76.840487  nominatim_dedup
451                                               Детский сад "Айсана"           мкр. Алмас, 134  43.212152  76.840487  nominatim_dedup
473                                             Детский сад "Ару kids"           мкр. Алмас, 201  43.212152  76.840487  nominatim_dedup
493                                            Детский сад "Садок ltd"           мкр. Алмас, 172  43.212152  76.840487  nominatim_dedup
431                                                Мини-центр "i.Bala"          мкр. Мамыр 4, 18  43.214040  76.854358              NaN
467                                             Детский сад "i.Bala 2"          мкр. Мамыр 4, 18  43.214040  76.854358  nominatim_dedup
337                                          Детский сад "ERKE A kids"       ул. Тажибаевой, 180  43.214124  76.891300        nominatim
384                                    Детский сад "Joy Art Education"       ул. Тажибаевой, 180  43.214124  76.891300        nominatim
404                                           Детский сад "Таргап А&K"         мкр. Мамыр 4, 128  43.214311  76.844594              NaN
486                                               Детский сад "ШамШер"         мкр. Мамыр 4, 128  43.214311  76.844594  nominatim_dedup
397                                             Детский сад "Умка Сад"         мкр. Мамыр-4, 166  43.215713  76.852208  nominatim_dedup
435                                               Детский сад "Эврика"          мкр. Мамыр 4, 4Б  43.215713  76.852208  nominatim_dedup
461                                                Детский сад "Білім"          мкр. Мамыр 4, 4б  43.215713  76.852208  nominatim_dedup
148                                           Детский сад "Дария Айша"      ул. Қыдырбеков, 60/1  43.215998  76.804259           yandex
188                                              Детский сад "Bаmbino"     ул. Кыдырбекова, 60/1  43.215998  76.804259           yandex
100                                           Детский сад "CӘТ-БЕРЕКЕ"      ул. Жунисова, 134/80  43.218856  76.790825  nominatim_dedup
106                                          Детский сад "Aizere 2020"        ул. Жунисова, 2/87  43.218856  76.790825        nominatim
127                                            Мини-центр "Чудо-детки"           ул. Таргап, 111  43.219009  76.795306        nominatim
162                                       Детский сад "Smart Children"           ул. Таргап, 111  43.219009  76.795306        nominatim
78   Детский сад "Алматинская математико-лингвистическая школа "Самай"    ул. Аширбек Сыгай, 124  43.220923  76.792445        nominatim
82                                        Детский сад "Munarat Almaty"     ул. Аширбек Сыгай, 96  43.220923  76.792445  nominatim_dedup
227                                        Детский сад "Villa Bambini"         ул. Таттимбета, 3  43.223372  76.967799        nominatim
248                                      Детский сад "Чудесная страна"         ул. Таттимбета, 3  43.223372  76.967799        nominatim
134                                           Детский сад "Бала-Дария"       ул. Айбергенова, 92  43.223932  76.796668  nominatim_dedup
137                                               Детский сад "Сұңқар"       ул. Айбергенова, 92  43.223932  76.796668  nominatim_dedup
474                                                Детский сад "Зере "        мкр. Атамекен, 70Б  43.236392  76.945728  nominatim_dedup
550                                                Детский сад "Арман"     мкр. Мадениет, 288/30  43.236392  76.945728  nominatim_dedup
456                                    Образовательный центр "Арайлым"          мкр. Баянаул, 40  43.239704  76.819395  nominatim_dedup
497                                        Детский сад "Мир детства 1"          мкр. Баянаул, 40  43.239704  76.819395              NaN
580                                         Детский сад "Болашақ и Со"    ул. Казтуган Жырау, 21  43.247665  76.813290        nominatim
699                                 ТОО "Детский сад "Мың бала Алматы"  ул. Казтуган Жырау, 29/1  43.247665  76.813290  nominatim_dedup
567                                          Мини-центр "ЕЛАМАН-КЫЗЫР"          ул. Чуланова, 83  43.253778  76.828289        nominatim
652                                        ТОО детский сад "БАЛ САПАР"          ул. Чуланова, 83  43.253778  76.828289        nominatim
522                                 Детский сад "Алди-Ерке-1" (филиал)        мкр. Туркестан, 77  43.271812  76.852261              NaN
686                                                 ТОО "АҚСАУЛЕ 2023"        мкр. Туркестан, 77  43.271812  76.852261              NaN
556                                           Детский сад "Кун Шуак-М"        ул. Туймебаева, 68  43.275548  76.834737        nominatim
624                                       ТОО "BAL-bala 1 балабақшасы"        ул. Туймебаева, 39  43.275548  76.834737  nominatim_dedup
528                                        Детский сад "Мерей компани"             ул. Текес, 67  43.284888  76.836085  nominatim_dedup
592                                      ТОО детский сад "Төре - Зере"             ул. Текес, 79  43.284888  76.836085        nominatim
39                                          Мини-центр "ЕРКЕМ-АЙ ГОЛД"          ул. Ижевская, 33  43.294301  76.962759        nominatim
49                                             Детский сад "Балдаурен"          ул. Ижевская, 33  43.294301  76.962759  nominatim_dedup
3                                       Мини-центр "Немере и компания"    ул. Каракалпакская, 12  43.296459  76.963379        nominatim
46                                            Детский сад "Bakutalemi"    ул. Каракалпакская, 12  43.296459  76.963379        nominatim
553                                              Детский сад "Зерде-2"          ул. Тайконыр, 41  43.300208  76.890733  nominatim_dedup
581                                                Детский сад "Зерде"          ул. Тайконыр, 41  43.300208  76.890733  nominatim_dedup
651                                          ТОО Ясли сад «Happy kids»  ул. Кожаберген Жырау, 19  43.327219  76.897735        nominatim
667                                       ТОО детский сад "Бақыт нұры"  ул. Кожаберген Жырау, 19  43.327219  76.897735        nominatim
36                                            Детский сад "Жансая-Сәт"           ул. Зимняя, 18Б  43.352260  76.986999  nominatim_dedup
44                                              Детский сад "Биржан К"             ул. Зимняя, 2  43.352260  76.986999  nominatim_dedup
24                                              Детский сад "КҮН ШУАҚ"       ул. Дунентаева, 6/4  43.357280  76.995136  nominatim_dedup
47                                               Детский сад "Кокетай"       ул. Дунентаева, 8/1  43.357280  76.995136  nominatim_dedup

In [52]:
dup_mask = df.duplicated(subset=["lat","lon"], keep=False)
dups = df[dup_mask].copy()

print("=== ОДИНАКОВЫЙ АДРЕС (два сада в одном здании) ===\n")
for (lat, lon), group in dups.groupby(["lat","lon"]):
    if group["address"].nunique() == 1:
        print(f"Адрес: {group['address'].iloc[0]}")
        for _, row in group.iterrows():
            print(f"  - {row['name']}")
        print()

=== ОДИНАКОВЫЙ АДРЕС (два сада в одном здании) ===

In [67]:
df = df[~df["name"].str.contains('ДиДи2016" (филиал)', na=False)]

C:\Users\Subbota\AppData\Local\Temp\ipykernel_25940\197973294.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df = df[~df["name"].str.contains('ДиДи2016" (филиал)', na=False)]

In [ ]:
df.loc[df['name']=='Детский сад "Еркем-ай"', 'address'] = 'ул. Парасат, 1'

In [79]:
df = df[df["name"] != 'Детский сад «Бала- Дария» филиал']

In [92]:
df.to_csv("kindergartens_almaty_private_osm_matched_final.csv", index=False)

In [84]:
df[df["name"].str.contains("Солнышко", na=False)]

,name,address,phone,type,email,lat,lon,method,score,confidence,match_method,money
193,"Мини центр ""Солнышко kz""","ул. Татибекова, 59/33","87758976758, 87273742575",дошкольный мини-центр,radik_avakriyev@mail.ru,43.2769,76.964097,nominatim,NaN,medium,NaN,yes

In [31]:
new_row = {
    "name": 'Детский сад "Бал-Дария-4"',
    "address": 'мкр. Достык, 128',
    "lat": 43.217869,
    "lon": 76.796721,
    'money': 'yes',
    'email': '',
    'phone': '',
    'type': 'частный детский сад'
}
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

In [ ]:
df.loc[df['name']=='Детский сад "Хан-Тәңірі-7"', 'lat'] = 43.274073
df.loc[df['name']=='Детский сад "Хан-Тәңірі-7"', 'lon'] = 76.845019

df.loc[df['name']=='Детский сад "Тұмар-А"', 'lat'] = 43.264514
df.loc[df['name']=='Детский сад "Тұмар-А"', 'lon'] = 76.790379

df.loc[df['name']=='Детский сад "Мәржол"', 'lat'] = 43.322593
df.loc[df['name']=='Детский сад "Мәржол"', 'lon'] = 76.841194

df.loc[df['name']=='ТОО "Балабакша "Болашақ"', 'lat'] = 43.336902
df.loc[df['name']=='ТОО "Балабакша "Болашақ"', 'lon'] = 76.844629

In [4]:
import pandas as pd
import re
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
from tqdm import tqdm

df = pd.read_csv("kindergartens_almaty_osm_matched_final.csv")

# viewbox Алматы
ALMATY_VIEWBOX = [(43.45, 76.70), (43.10, 77.15)]

geolocator = Nominatim(user_agent="almaty-clean-pass", timeout=20)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)


def clean_address(addr):
    if pd.isna(addr):
        return ""

    s = str(addr)
    s = s.replace("мкр.", "микрорайон")
    s = s.replace("ул.", "улица")
    s = s.replace("пр.", "проспект")
    s = re.sub(r"\s+", " ", s).strip(" ,")
    return s


def address_variants(addr):
    a = clean_address(addr)
    variants = [a]

    # без микрорайона
    v2 = re.sub(r"микрорайон[^,]+,\s*", "", a, flags=re.IGNORECASE)
    variants.append(v2)

    # только улица + дом
    m = re.search(r"(улица[^,]+,\s*\d+\w?)", a, flags=re.IGNORECASE)
    if m:
        variants.append(m.group(1))

    # убрать слова
    v4 = re.sub(r"(микрорайон|улица|проспект)", "", a, flags=re.IGNORECASE)
    variants.append(v4)

    # удалить пустые
    return list(dict.fromkeys([v.strip(" ,") for v in variants if v.strip()]))
import requests

def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15


photon_cache = {}

def photon_geocode(q):
    if q in photon_cache:
        return photon_cache[q]

    url = "https://photon.komoot.io/api"

    try:
        r = requests.get(url, params={"q": q, "limit": 1}, timeout=10)
        js = r.json()
        feats = js.get("features", [])

        if feats:
            lon, lat = feats[0]["geometry"]["coordinates"]

            if in_bbox(lat, lon):
                photon_cache[q] = (lat, lon)
                return lat, lon

    except:
        pass

    photon_cache[q] = (None, None)
    return None, None

def multi_geocode(addr):
    queries = [
        f"{addr}, Алматы, Казахстан",
        f"детский сад {addr}, Алматы",
        f"{addr}, Almaty, Kazakhstan"
    ]
    
    for q in queries:
        lat, lon = photon_geocode(q)
        if lat:
            return lat, lon
    
    return None, None
def geo(q):
    try:
        loc = geocode(q, viewbox=ALMATY_VIEWBOX, bounded=True, country_codes="kz")
        if loc:
            return loc.latitude, loc.longitude
    except:
        pass
    return None, None


mask = df["lat"].isna()

for i in tqdm(df[mask].index):
    addr = df.loc[i, "address"]
    for v in address_variants(addr):

        # 1. Photon
        lat, lon = multi_geocode(v)
        if lat is not None:
            df.loc[i, "lat"] = lat
            df.loc[i, "lon"] = lon
            df.loc[i, "match_method"] = "photon_clean"
            break

        # 2. Nominatim fallback
        lat, lon = geo(v)
        if lat is not None:
            df.loc[i, "lat"] = lat
            df.loc[i, "lon"] = lon
            df.loc[i, "match_method"] = "nominatim_clean"
            break

df.to_csv("kindergartens_almaty_osm_final.csv", index=False)

print("Найдено:", df["lat"].notna().sum())
print("Не найдено:", df["lat"].isna().sum())

100%|██████████| 22/22 [00:48<00:00,  2.22s/it]

Найдено: 197
Не найдено: 1

In [5]:
not_found = df[df["lat"].isna()].copy()
not_found

,name,address,phone,type,email,lat,lon,method,score,confidence,match_method
113,"КГКП ""Ясли-сад №87""","ул. Си-Синхая, 14","87015031313, 87273964336",ясли-сад,Sadik87@list.ru,NaN,NaN,NaN,NaN,low,NaN

In [91]:
import pandas as pd


dup_mask = df.duplicated(subset=["lat","lon"], keep=False)
dup_mask = dup_mask & df["lat"].notna()
dups = df[dup_mask].copy()

print("=== ОДИНАКОВЫЙ АДРЕС ===\n")
same_addr_count = 0
for (lat, lon), group in dups.groupby(["lat","lon"]):
    if group["address"].nunique() == 1:
        same_addr_count += 1
        print(f"Адрес: {group['address'].iloc[0]}")
        for _, row in group.iterrows():
            print(f"  - {row['name']}")
        print()

print(f"Всего групп с одинаковым адресом: {same_addr_count}")
print()

print("=== РАЗНЫЕ АДРЕСА (промах геокодера) ===\n")
diff_addr_count = 0
for (lat, lon), group in dups.groupby(["lat","lon"]):
    if group["address"].nunique() > 1:
        diff_addr_count += 1
        print(f"Точка: {lat}, {lon}")
        for _, row in group.iterrows():
            print(f"  - {row['name']} | {row['address']}")
        print()
        

print(f"Всего групп с разными адресами: {diff_addr_count}")

=== ОДИНАКОВЫЙ АДРЕС ===

Всего групп с одинаковым адресом: 0

=== РАЗНЫЕ АДРЕСА (промах геокодера) ===

Всего групп с разными адресами: 0

In [57]:
import pandas as pd
import requests
import time
import re

df = pd.read_csv("kindergartens_almaty_private_osm_matched_final.csv")

YANDEX_KEY = "4e0aaf8d-4ab5-4be2-be63-7327bbe09df2"

def in_bbox(lat, lon):
    return 43.10 <= lat <= 43.45 and 76.70 <= lon <= 77.15

def clean(addr):
    addr = str(addr).strip()
    addr = re.sub(r'\bул\.\s*', '', addr)
    addr = re.sub(r'\bпр\.\s*', '', addr)
    addr = re.sub(r'\bпр-т\s*', '', addr)
    addr = re.sub(r'\bмкр\.\s*', 'микрорайон ', addr)
    addr = re.sub(r'\bпер\.\s*', '', addr)
    addr = re.sub(r'\s+', ' ', addr).strip(' ,')
    return addr

def yandex_geocode(addr):
    c = clean(addr)
    variants = [
        f"Алматы, {addr}",
        f"Алматы, {c}",
        f"Алматы {c}",
        f"Казахстан, Алматы, {c}",
    ]
    for q in variants:
        try:
            r = requests.get(
                "https://geocode-maps.yandex.ru/1.x/",
                params={
                    "apikey": YANDEX_KEY,
                    "geocode": q,
                    "format": "json",
                    "ll": "76.89,43.24",
                    "spn": "0.35,0.25",
                    "rspn": 1,
                    "results": 1,
                    "lang": "ru_RU"
                },
                timeout=10
            )
            members = r.json()["response"]["GeoObjectCollection"]["featureMember"]
            if members:
                pos = members[0]["GeoObject"]["Point"]["pos"].split()
                lon, lat = float(pos[0]), float(pos[1])
                if in_bbox(lat, lon):
                    return lat, lon, q
        except Exception as e:
            print(f"  ошибка: {e}")
        time.sleep(0.2)
    return None, None, None

# ── 1. Геокодируем NaN ──────────────────────────────────────────────
to_fix = df[df["lat"].isna()].index.tolist()
print(f"Геокодируем NaN: {len(to_fix)} адресов\n")

found = 0
not_found = []

for i in to_fix:
    addr = str(df.loc[i, "address"])
    name = df.loc[i, "name"]
    lat, lon, matched_q = yandex_geocode(addr)
    if lat:
        df.loc[i, "lat"] = lat
        df.loc[i, "lon"] = lon
        df.loc[i, "method"] = "yandex"
        print(f"✓ {name[:45]}")
        print(f"  {addr} → {lat:.5f}, {lon:.5f}")
        found += 1
    else:
        not_found.append({"name": name, "address": addr})
        print(f"✗ {name[:45]} | {addr}")
    time.sleep(0.2)

print(f"\nNaN: найдено {found}/{len(to_fix)}")

# ── 2. Исправляем дубликаты координат (промахи геокодера) ───────────
print("\n" + "="*50)
print("Исправляем дубликаты координат...\n")

dup_mask = df.duplicated(subset=["lat", "lon"], keep=False) & df["lat"].notna()
dups = df[dup_mask].copy()

dup_fixed = 0
dup_not_found = []

for (lat, lon), group in dups.groupby(["lat", "lon"]):
    # Пропускаем группы с одинаковым адресом — там дубликат настоящий
    if group["address"].nunique() == 1:
        continue

    print(f"Точка {lat}, {lon} — {len(group)} садиков с разными адресами:")

    for i, row in group.iterrows():
        addr = str(row["address"])
        name = row["name"]

        new_lat, new_lon, matched_q = yandex_geocode(addr)

        if new_lat and (new_lat != lat or new_lon != lon):
            df.loc[i, "lat"] = new_lat
            df.loc[i, "lon"] = new_lon
            df.loc[i, "method"] = "yandex_dedup"
            print(f"  ✓ {name[:40]}")
            print(f"    {addr} → {new_lat:.5f}, {new_lon:.5f}")
            dup_fixed += 1
        else:
            # Геокодер снова вернул ту же точку или ничего — обнуляем
            df.loc[i, "lat"] = None
            df.loc[i, "lon"] = None
            df.loc[i, "method"] = "dedup_failed"
            dup_not_found.append({"name": name, "address": addr})
            print(f"  ✗ {name[:40]} | {addr} — обнулено")

        time.sleep(0.2)
    print()

# ── 3. Итог ─────────────────────────────────────────────────────────
print("="*50)
print(f"NaN геокодировано:       {found}/{len(to_fix)}")
print(f"Дубликатов исправлено:   {dup_fixed}")
print(f"Осталось NaN:            {df['lat'].isna().sum()}")
print(f"Осталось дубликатов:     {df.duplicated(subset=['lat','lon']).sum()}")

df.to_csv("kindergartens_almaty_private_osm_matched_final.csv", index=False)

all_not_found = not_found + dup_not_found
if all_not_found:
    pd.DataFrame(all_not_found).to_csv("still_not_found.csv", index=False)
    print(f"\nНе найдено → still_not_found.csv ({len(all_not_found)} штук)")

Геокодируем NaN: 6 адресов

✗ Детский сад "АЗИМКА" | ул. Дегдара, 36/1
✗ Детский сад «Бала- Дария» филиал | ул. Аширбек Сыгай, 55
✗ Детский сад "АЯНАТ" | ул. Аскарова, 28
✗ Детский сад "Мадина -27" | ул. Молодежная, 69А
✗ Детский сад «ЭЛКО» | мкр. Орбита 3, 8а
✗ Детский сад "Ахмадиева" | ул. Подгорная, 25/2

NaN: найдено 0/6

==================================================
Исправляем дубликаты координат...

Точка 43.2121518, 76.8404866 — 5 садиков с разными адресами:
  ✓ Детский сад "Altyn Gasyr_KZ"
    мкр. Мамыр-7, 21 → 43.21009, 76.84090
  ✓ Детский сад "Antaress kids-2"
    мкр. Алмас, 106 → 43.20608, 76.83980
  ✓ Детский сад "Айсана"
    мкр. Алмас, 134 → 43.20437, 76.84146
  ✓ Детский сад "Ару kids"
    мкр. Алмас, 201 → 43.20685, 76.84215
  ✓ Детский сад "Садок ltd"
    мкр. Алмас, 172 → 43.20504, 76.84245

Точка 43.2147988, 76.8692698 — 2 садиков с разными адресами:
  ✓ Детский сад "Lion Garden"
    мкр. Алмас, 57а → 43.20770, 76.83878
  ✓ Детский сад "УМКА"
    мкр. Мамыр-4, 57А → 43.21631, 76.84888

Точка 43.2157126, 76.852208 — 3 садиков с разными адресами:
  ✓ Детский сад "Умка Сад"
    мкр. Мамыр-4, 166 → 43.21511, 76.84803
  ✓ Детский сад "Эврика"
    мкр. Мамыр 4, 4Б → 43.21713, 76.84590
  ✓ Детский сад "Білім"
    мкр. Мамыр 4, 4б → 43.21713, 76.84590

Точка 43.2157544, 76.8374099 — 2 садиков с разными адресами:
  ✓ Мини-центр "Новое поколение"
    мкр. Мамыр 7, 8/1 → 43.21577, 76.83745
  ✓ Мини-центр "ДиДи2016" (филиал)
    мкр. Мамыр-7, 8/1 → 43.21577, 76.83745

Точка 43.215998, 76.804259 — 2 садиков с разными адресами:
  ✗ Детский сад "Дария Айша" | ул. Қыдырбеков, 60/1 — обнулено
  ✗ Детский сад "Bаmbino" | ул. Кыдырбекова, 60/1 — обнулено

Точка 43.2160515, 76.8498058 — 2 садиков с разными адресами:
  ✓ Детский сад "Antaress Kids"
    мкр. Мамыр-4, 156 → 43.21606, 76.84987
  ✓ Мини-центр "АйДиНур"
    мкр. Мамыр 4, 156 → 43.21606, 76.84987

Точка 43.2188564, 76.7908251 — 2 садиков с разными адресами:
  ✓ Детский сад "CӘТ-БЕРЕКЕ"
    ул. Жунисова, 134/80 → 43.21745, 76.79137
  ✗ Детский сад "Aizere 2020" | ул. Жунисова, 2/87 — обнулено

Точка 43.2190093, 76.7953065 — 2 садиков с разными адресами:
  ✓ Мини-центрЕртегі әлемі
    ул. Таргап, 111 → 43.21901, 76.79535
  ✓ Детский сад "Smart Children"
    ул. Таргап, 118 → 43.21899, 76.79467

Точка 43.220923, 76.7924448 — 2 садиков с разными адресами:
  ✓ Детский сад "Алматинская математико-линг
    ул. Аширбек Сыгай, 124 → 43.21825, 76.79387
  ✓ Детский сад "Munarat Almaty"
    ул. Аширбек Сыгай, 96 → 43.22056, 76.79245

Точка 43.2233719, 76.9677989 — 2 садиков с разными адресами:
  ✓ Детский сад "Villa Bambini"
    ул. Таттимбета, 3 → 43.22367, 76.96773
  ✓ Детский сад "Чудесная страна"
    ул. Радлова, 22 → 43.24374, 76.97385

Точка 43.2356935, 76.8265453 — 2 садиков с разными адресами:
  ✓ Детский Центр "Умка"
    мкр. Аксай 3а, 85 → 43.23747, 76.82600
  ✓ Детский сад "СӘТТІЛІК & БОЛАШАҚ"
    мкр. Мамыр 3, 3А → 43.21278, 76.85256

Точка 43.2363924, 76.9457275 — 3 садиков с разными адресами:
  ✓ Детский сад "Parasat-S"
    мкр. Айнабулак-3, 172Е → 43.32309, 76.91604
  ✓ Детский сад "Зере "
    мкр. Атамекен, 70Б → 43.20840, 76.84569
  ✗ Детский сад "Арман" | мкр. Мадениет, 288/30 — обнулено

Точка 43.2476647, 76.8132905 — 2 садиков с разными адресами:
  ✓ Детский сад "Болашақ и Со"
    ул. Казтуган Жырау, 21 → 43.24889, 76.81242
  ✓ ТОО "Детский сад "Мың бала Алматы"
    ул. Казтуган Жырау, 29/1 → 43.24969, 76.81196

Точка 43.2755482, 76.8347368 — 2 садиков с разными адресами:
  ✓ Детский сад "Кун Шуак-М"
    ул. Туймебаева, 68 → 43.27468, 76.83434
  ✓ ТОО "BAL-bala 1 балабақшасы"
    ул. Туймебаева, 39 → 43.27733, 76.83533

Точка 43.2848883, 76.8360854 — 2 садиков с разными адресами:
  ✓ Детский сад "Мерей компани"
    ул. Текес, 67 → 43.28547, 76.84052
  ✓ ТОО детский сад "Төре - Зере"
    ул. Текес, 79 → 43.28565, 76.84263

Точка 43.3522603, 76.9869989 — 2 садиков с разными адресами:
  ✓ Детский сад "Жансая-Сәт"
    ул. Зимняя, 18Б → 43.35303, 76.98742
  ✓ Детский сад "Биржан К"
    ул. Зимняя, 2 → 43.35330, 76.98923

Точка 43.3572796, 76.9951357 — 2 садиков с разными адресами:
  ✓ Детский сад "КҮН ШУАҚ"
    ул. Дунентаева, 6/4 → 43.35604, 76.99448
  ✓ Детский сад "Кокетай"
    ул. Дунентаева, 8/1 → 43.35616, 76.99554

==================================================
NaN геокодировано:       0/6
Дубликатов исправлено:   35
Осталось NaN:            10
Осталось дубликатов:     12

Не найдено → still_not_found.csv (10 штук)

In [89]:
# Диагностика после прогона
print("=== Оставшиеся NaN ===")
print(df[df["lat"].isna()][["name", "address"]].to_string())

print("\n=== Оставшиеся дубликаты ===")
dup_mask = df.duplicated(subset=["lat","lon"], keep=False) & df["lat"].notna()
dups = df[dup_mask].copy()
for (lat, lon), group in dups.groupby(["lat","lon"]):
    print(f"\nТочка {lat:.5f}, {lon:.5f}:")
    for _, row in group.iterrows():
        print(f"  - {row['name']} | {row['address']} | method={row.get('method','')}")

=== Оставшиеся NaN ===
Empty DataFrame
Columns: [name, address]
Index: []

=== Оставшиеся дубликаты ===

In [88]:
df.loc[df['name']=='Детский сад "Арман"', 'lat'] = 43.337703
df.loc[df['name']=='Детский сад "Арман"', 'lon'] = 76.81359

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 726 entries, 0 to 727
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          726 non-null    object
 1   address       726 non-null    object
 2   phone         720 non-null    object
 3   type          724 non-null    object
 4   email         719 non-null    object
 5   lat           726 non-null    float64
 6   lon           726 non-null    float64
 7   method        577 non-null    object
 8   score         265 non-null    float64
 9   confidence    721 non-null    object
 10  match_method  98 non-null     object
 11  money         726 non-null    object
dtypes: float64(3), object(9)
memory usage: 73.7+ KB

In [ ]:
df.drop(columns=[""], inplace=True)

In [1]:
import osmnx as ox

north = 43.35
south = 43.15
east = 77.10
west = 76.70

G = ox.graph_from_place(
    "Almaty, Kazakhstan",
    network_type="walk"
)

ox.save_graphml(G, "almaty_walk_q01_q99.graphml")